{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='user', url='', help='"User is the Schema for the Users API."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of User', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'users.azuread.upbound.io/v1beta1',
    kind: 'User',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"UserSpec defines the desired state of User"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#passwordSecretRef':: d.obj(help='"The password for the user. The password must satisfy minimum requirements as specified by the password policy. The maximum length is 256 characters. This property is required when creating a new user.\\nThe password for the user. The password must satisfy minimum requirements as specified by the password policy. The maximum length is 256 characters. This property is required when creating a new user"'),
      passwordSecretRef: {
        '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { spec+: { forProvider+: { passwordSecretRef+: { key: key } } } },
        '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { passwordSecretRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { forProvider+: { passwordSecretRef+: { namespace: namespace } } } },
      },
      '#withAccountEnabled':: d.fn(help='"Whether or not the account should be enabled.\\nWhether or not the account should be enabled"', args=[d.arg(name='accountEnabled', type=d.T.boolean)]),
      withAccountEnabled(accountEnabled): { spec+: { forProvider+: { accountEnabled: accountEnabled } } },
      '#withAgeGroup':: d.fn(help='"The age group of the user. Supported values are Adult, NotAdult and Minor. Omit this property or specify a blank string to unset.\\nThe age group of the user"', args=[d.arg(name='ageGroup', type=d.T.string)]),
      withAgeGroup(ageGroup): { spec+: { forProvider+: { ageGroup: ageGroup } } },
      '#withBusinessPhones':: d.fn(help='"A list of telephone numbers for the user. Only one number can be set for this property. Read-only for users synced with Azure AD Connect.\\nThe telephone numbers for the user. Only one number can be set for this property. Read-only for users synced with Azure AD Connect"', args=[d.arg(name='businessPhones', type=d.T.array)]),
      withBusinessPhones(businessPhones): { spec+: { forProvider+: { businessPhones: if std.isArray(v=businessPhones) then businessPhones else [businessPhones] } } },
      '#withBusinessPhonesMixin':: d.fn(help='"A list of telephone numbers for the user. Only one number can be set for this property. Read-only for users synced with Azure AD Connect.\\nThe telephone numbers for the user. Only one number can be set for this property. Read-only for users synced with Azure AD Connect"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='businessPhones', type=d.T.array)]),
      withBusinessPhonesMixin(businessPhones): { spec+: { forProvider+: { businessPhones+: if std.isArray(v=businessPhones) then businessPhones else [businessPhones] } } },
      '#withCity':: d.fn(help='"The city in which the user is located.\\nThe city in which the user is located"', args=[d.arg(name='city', type=d.T.string)]),
      withCity(city): { spec+: { forProvider+: { city: city } } },
      '#withCompanyName':: d.fn(help='"The company name which the user is associated. This property can be useful for describing the company that an external user comes from.\\nThe company name which the user is associated. This property can be useful for describing the company that an external user comes from"', args=[d.arg(name='companyName', type=d.T.string)]),
      withCompanyName(companyName): { spec+: { forProvider+: { companyName: companyName } } },
      '#withConsentProvidedForMinor':: d.fn(help='"Whether consent has been obtained for minors. Supported values are Granted, Denied and NotRequired. Omit this property or specify a blank string to unset.\\nWhether consent has been obtained for minors"', args=[d.arg(name='consentProvidedForMinor', type=d.T.string)]),
      withConsentProvidedForMinor(consentProvidedForMinor): { spec+: { forProvider+: { consentProvidedForMinor: consentProvidedForMinor } } },
      '#withCostCenter':: d.fn(help='"The cost center associated with the user.\\nThe cost center associated with the user."', args=[d.arg(name='costCenter', type=d.T.string)]),
      withCostCenter(costCenter): { spec+: { forProvider+: { costCenter: costCenter } } },
      '#withCountry':: d.fn(help='"The country/region in which the user is located. Examples include: NO, JP, and GB.\\nThe country/region in which the user is located, e.g. `US` or `UK`"', args=[d.arg(name='country', type=d.T.string)]),
      withCountry(country): { spec+: { forProvider+: { country: country } } },
      '#withDepartment':: d.fn(help='"The name for the department in which the user works.\\nThe name for the department in which the user works"', args=[d.arg(name='department', type=d.T.string)]),
      withDepartment(department): { spec+: { forProvider+: { department: department } } },
      '#withDisablePasswordExpiration':: d.fn(help="\"Whether the user's password is exempt from expiring. Defaults to false.\\nWhether the users password is exempt from expiring\"", args=[d.arg(name='disablePasswordExpiration', type=d.T.boolean)]),
      withDisablePasswordExpiration(disablePasswordExpiration): { spec+: { forProvider+: { disablePasswordExpiration: disablePasswordExpiration } } },
      '#withDisableStrongPassword':: d.fn(help='"Whether the user is allowed weaker passwords than the default policy to be specified. Defaults to false.\\nWhether the user is allowed weaker passwords than the default policy to be specified."', args=[d.arg(name='disableStrongPassword', type=d.T.boolean)]),
      withDisableStrongPassword(disableStrongPassword): { spec+: { forProvider+: { disableStrongPassword: disableStrongPassword } } },
      '#withDisplayName':: d.fn(help='"The name to display in the address book for the user.\\nThe name to display in the address book for the user"', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { forProvider+: { displayName: displayName } } },
      '#withDivision':: d.fn(help='"The name of the division in which the user works.\\nThe name of the division in which the user works."', args=[d.arg(name='division', type=d.T.string)]),
      withDivision(division): { spec+: { forProvider+: { division: division } } },
      '#withEmployeeHireDate':: d.fn(help='"The hire date of the user, formatted as an RFC3339 date string (e.g. 2018-01-01T01:02:03Z).\\nThe hire date of the user, formatted as an RFC3339 date string (e.g. `2018-01-01T01:02:03Z`)."', args=[d.arg(name='employeeHireDate', type=d.T.string)]),
      withEmployeeHireDate(employeeHireDate): { spec+: { forProvider+: { employeeHireDate: employeeHireDate } } },
      '#withEmployeeId':: d.fn(help='"The employee identifier assigned to the user by the organisation.\\nThe employee identifier assigned to the user by the organisation"', args=[d.arg(name='employeeId', type=d.T.string)]),
      withEmployeeId(employeeId): { spec+: { forProvider+: { employeeId: employeeId } } },
      '#withEmployeeType':: d.fn(help='"Captures enterprise worker type. For example, Employee, Contractor, Consultant, or Vendor.\\nCaptures enterprise worker type. For example, Employee, Contractor, Consultant, or Vendor."', args=[d.arg(name='employeeType', type=d.T.string)]),
      withEmployeeType(employeeType): { spec+: { forProvider+: { employeeType: employeeType } } },
      '#withFaxNumber':: d.fn(help='"The fax number of the user.\\nThe fax number of the user"', args=[d.arg(name='faxNumber', type=d.T.string)]),
      withFaxNumber(faxNumber): { spec+: { forProvider+: { faxNumber: faxNumber } } },
      '#withForcePasswordChange':: d.fn(help='"Whether the user is forced to change the password during the next sign-in. Only takes effect when also changing the password. Defaults to false.\\nWhether the user is forced to change the password during the next sign-in. Only takes effect when also changing the password"', args=[d.arg(name='forcePasswordChange', type=d.T.boolean)]),
      withForcePasswordChange(forcePasswordChange): { spec+: { forProvider+: { forcePasswordChange: forcePasswordChange } } },
      '#withGivenName':: d.fn(help='"The given name (first name) of the user.\\nThe given name (first name) of the user"', args=[d.arg(name='givenName', type=d.T.string)]),
      withGivenName(givenName): { spec+: { forProvider+: { givenName: givenName } } },
      '#withJobTitle':: d.fn(help='"The user’s job title.\\nThe user’s job title"', args=[d.arg(name='jobTitle', type=d.T.string)]),
      withJobTitle(jobTitle): { spec+: { forProvider+: { jobTitle: jobTitle } } },
      '#withMail':: d.fn(help='"The SMTP address for the user. This property cannot be unset once specified.\\nThe SMTP address for the user. Cannot be unset."', args=[d.arg(name='mail', type=d.T.string)]),
      withMail(mail): { spec+: { forProvider+: { mail: mail } } },
      '#withMailNickname':: d.fn(help='"The mail alias for the user. Defaults to the user name part of the user principal name (UPN).\\nThe mail alias for the user. Defaults to the user name part of the user principal name (UPN)"', args=[d.arg(name='mailNickname', type=d.T.string)]),
      withMailNickname(mailNickname): { spec+: { forProvider+: { mailNickname: mailNickname } } },
      '#withManagerId':: d.fn(help="\"The object ID of the user's manager.\\nThe object ID of the user's manager\"", args=[d.arg(name='managerId', type=d.T.string)]),
      withManagerId(managerId): { spec+: { forProvider+: { managerId: managerId } } },
      '#withMobilePhone':: d.fn(help='"The primary cellular telephone number for the user.\\nThe primary cellular telephone number for the user"', args=[d.arg(name='mobilePhone', type=d.T.string)]),
      withMobilePhone(mobilePhone): { spec+: { forProvider+: { mobilePhone: mobilePhone } } },
      '#withOfficeLocation':: d.fn(help="\"The office location in the user's place of business.\\nThe office location in the user's place of business\"", args=[d.arg(name='officeLocation', type=d.T.string)]),
      withOfficeLocation(officeLocation): { spec+: { forProvider+: { officeLocation: officeLocation } } },
      '#withOnpremisesImmutableId':: d.fn(help="\"The value used to associate an on-premise Active Directory user account with their Azure AD user object. This must be specified if you are using a federated domain for the user's user_principal_name property when creating a new user account.\\nThe value used to associate an on-premise Active Directory user account with their Azure AD user object. This must be specified if you are using a federated domain for the user's `user_principal_name` property when creating a new user account\"", args=[d.arg(name='onpremisesImmutableId', type=d.T.string)]),
      withOnpremisesImmutableId(onpremisesImmutableId): { spec+: { forProvider+: { onpremisesImmutableId: onpremisesImmutableId } } },
      '#withOtherMails':: d.fn(help='"A list of additional email addresses for the user.\\nAdditional email addresses for the user"', args=[d.arg(name='otherMails', type=d.T.array)]),
      withOtherMails(otherMails): { spec+: { forProvider+: { otherMails: if std.isArray(v=otherMails) then otherMails else [otherMails] } } },
      '#withOtherMailsMixin':: d.fn(help='"A list of additional email addresses for the user.\\nAdditional email addresses for the user"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='otherMails', type=d.T.array)]),
      withOtherMailsMixin(otherMails): { spec+: { forProvider+: { otherMails+: if std.isArray(v=otherMails) then otherMails else [otherMails] } } },
      '#withPostalCode':: d.fn(help="\"The postal code for the user's postal address. The postal code is specific to the user's country/region. In the United States of America, this attribute contains the ZIP code.\\nThe postal code for the user's postal address. The postal code is specific to the user's country/region. In the United States of America, this attribute contains the ZIP code\"", args=[d.arg(name='postalCode', type=d.T.string)]),
      withPostalCode(postalCode): { spec+: { forProvider+: { postalCode: postalCode } } },
      '#withPreferredLanguage':: d.fn(help="\"The user's preferred language, in ISO 639-1 notation.\\nThe user's preferred language, in ISO 639-1 notation\"", args=[d.arg(name='preferredLanguage', type=d.T.string)]),
      withPreferredLanguage(preferredLanguage): { spec+: { forProvider+: { preferredLanguage: preferredLanguage } } },
      '#withShowInAddressList':: d.fn(help='"Whether or not the Outlook global address list should include this user. Defaults to true.\\nWhether or not the Outlook global address list should include this user"', args=[d.arg(name='showInAddressList', type=d.T.boolean)]),
      withShowInAddressList(showInAddressList): { spec+: { forProvider+: { showInAddressList: showInAddressList } } },
      '#withState':: d.fn(help="\"The state or province in the user's address.\\nThe state or province in the user's address\"", args=[d.arg(name='state', type=d.T.string)]),
      withState(state): { spec+: { forProvider+: { state: state } } },
      '#withStreetAddress':: d.fn(help="\"The street address of the user's place of business.\\nThe street address of the user's place of business\"", args=[d.arg(name='streetAddress', type=d.T.string)]),
      withStreetAddress(streetAddress): { spec+: { forProvider+: { streetAddress: streetAddress } } },
      '#withSurname':: d.fn(help="\"The user's surname (family name or last name).\\nThe user's surname (family name or last name)\"", args=[d.arg(name='surname', type=d.T.string)]),
      withSurname(surname): { spec+: { forProvider+: { surname: surname } } },
      '#withUsageLocation':: d.fn(help='"The usage location of the user. Required for users that will be assigned licenses due to legal requirement to check for availability of services in countries. The usage location is a two letter country code (ISO standard 3166). Examples include: NO, JP, and GB. Cannot be reset to null once set.\\nThe usage location of the user. Required for users that will be assigned licenses due to legal requirement to check for availability of services in countries. The usage location is a two letter country code (ISO standard 3166). Examples include: `NO`, `JP`, and `GB`. Cannot be reset to null once set"', args=[d.arg(name='usageLocation', type=d.T.string)]),
      withUsageLocation(usageLocation): { spec+: { forProvider+: { usageLocation: usageLocation } } },
      '#withUserPrincipalName':: d.fn(help='"The user principal name (UPN) of the user.\\nThe user principal name (UPN) of the user"', args=[d.arg(name='userPrincipalName', type=d.T.string)]),
      withUserPrincipalName(userPrincipalName): { spec+: { forProvider+: { userPrincipalName: userPrincipalName } } },
    },
    '#initProvider':: d.obj(help='"THIS IS A BETA FIELD. It will be honored\\nunless the Management Policies feature flag is disabled.\\nInitProvider holds the same fields as ForProvider, with the exception\\nof Identifier and other resource reference fields. The fields that are\\nin InitProvider are merged into ForProvider when the resource is created.\\nThe same fields are also added to the terraform ignore_changes hook, to\\navoid updating them after creation. This is useful for fields that are\\nrequired on creation, but we do not desire to update them after creation,\\nfor example because of an external controller is managing them, like an\\nautoscaler."'),
    initProvider: {
      '#passwordSecretRef':: d.obj(help='"The password for the user. The password must satisfy minimum requirements as specified by the password policy. The maximum length is 256 characters. This property is required when creating a new user.\\nThe password for the user. The password must satisfy minimum requirements as specified by the password policy. The maximum length is 256 characters. This property is required when creating a new user"'),
      passwordSecretRef: {
        '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { spec+: { initProvider+: { passwordSecretRef+: { key: key } } } },
        '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { initProvider+: { passwordSecretRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { initProvider+: { passwordSecretRef+: { namespace: namespace } } } },
      },
      '#withAccountEnabled':: d.fn(help='"Whether or not the account should be enabled.\\nWhether or not the account should be enabled"', args=[d.arg(name='accountEnabled', type=d.T.boolean)]),
      withAccountEnabled(accountEnabled): { spec+: { initProvider+: { accountEnabled: accountEnabled } } },
      '#withAgeGroup':: d.fn(help='"The age group of the user. Supported values are Adult, NotAdult and Minor. Omit this property or specify a blank string to unset.\\nThe age group of the user"', args=[d.arg(name='ageGroup', type=d.T.string)]),
      withAgeGroup(ageGroup): { spec+: { initProvider+: { ageGroup: ageGroup } } },
      '#withBusinessPhones':: d.fn(help='"A list of telephone numbers for the user. Only one number can be set for this property. Read-only for users synced with Azure AD Connect.\\nThe telephone numbers for the user. Only one number can be set for this property. Read-only for users synced with Azure AD Connect"', args=[d.arg(name='businessPhones', type=d.T.array)]),
      withBusinessPhones(businessPhones): { spec+: { initProvider+: { businessPhones: if std.isArray(v=businessPhones) then businessPhones else [businessPhones] } } },
      '#withBusinessPhonesMixin':: d.fn(help='"A list of telephone numbers for the user. Only one number can be set for this property. Read-only for users synced with Azure AD Connect.\\nThe telephone numbers for the user. Only one number can be set for this property. Read-only for users synced with Azure AD Connect"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='businessPhones', type=d.T.array)]),
      withBusinessPhonesMixin(businessPhones): { spec+: { initProvider+: { businessPhones+: if std.isArray(v=businessPhones) then businessPhones else [businessPhones] } } },
      '#withCity':: d.fn(help='"The city in which the user is located.\\nThe city in which the user is located"', args=[d.arg(name='city', type=d.T.string)]),
      withCity(city): { spec+: { initProvider+: { city: city } } },
      '#withCompanyName':: d.fn(help='"The company name which the user is associated. This property can be useful for describing the company that an external user comes from.\\nThe company name which the user is associated. This property can be useful for describing the company that an external user comes from"', args=[d.arg(name='companyName', type=d.T.string)]),
      withCompanyName(companyName): { spec+: { initProvider+: { companyName: companyName } } },
      '#withConsentProvidedForMinor':: d.fn(help='"Whether consent has been obtained for minors. Supported values are Granted, Denied and NotRequired. Omit this property or specify a blank string to unset.\\nWhether consent has been obtained for minors"', args=[d.arg(name='consentProvidedForMinor', type=d.T.string)]),
      withConsentProvidedForMinor(consentProvidedForMinor): { spec+: { initProvider+: { consentProvidedForMinor: consentProvidedForMinor } } },
      '#withCostCenter':: d.fn(help='"The cost center associated with the user.\\nThe cost center associated with the user."', args=[d.arg(name='costCenter', type=d.T.string)]),
      withCostCenter(costCenter): { spec+: { initProvider+: { costCenter: costCenter } } },
      '#withCountry':: d.fn(help='"The country/region in which the user is located. Examples include: NO, JP, and GB.\\nThe country/region in which the user is located, e.g. `US` or `UK`"', args=[d.arg(name='country', type=d.T.string)]),
      withCountry(country): { spec+: { initProvider+: { country: country } } },
      '#withDepartment':: d.fn(help='"The name for the department in which the user works.\\nThe name for the department in which the user works"', args=[d.arg(name='department', type=d.T.string)]),
      withDepartment(department): { spec+: { initProvider+: { department: department } } },
      '#withDisablePasswordExpiration':: d.fn(help="\"Whether the user's password is exempt from expiring. Defaults to false.\\nWhether the users password is exempt from expiring\"", args=[d.arg(name='disablePasswordExpiration', type=d.T.boolean)]),
      withDisablePasswordExpiration(disablePasswordExpiration): { spec+: { initProvider+: { disablePasswordExpiration: disablePasswordExpiration } } },
      '#withDisableStrongPassword':: d.fn(help='"Whether the user is allowed weaker passwords than the default policy to be specified. Defaults to false.\\nWhether the user is allowed weaker passwords than the default policy to be specified."', args=[d.arg(name='disableStrongPassword', type=d.T.boolean)]),
      withDisableStrongPassword(disableStrongPassword): { spec+: { initProvider+: { disableStrongPassword: disableStrongPassword } } },
      '#withDisplayName':: d.fn(help='"The name to display in the address book for the user.\\nThe name to display in the address book for the user"', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { initProvider+: { displayName: displayName } } },
      '#withDivision':: d.fn(help='"The name of the division in which the user works.\\nThe name of the division in which the user works."', args=[d.arg(name='division', type=d.T.string)]),
      withDivision(division): { spec+: { initProvider+: { division: division } } },
      '#withEmployeeHireDate':: d.fn(help='"The hire date of the user, formatted as an RFC3339 date string (e.g. 2018-01-01T01:02:03Z).\\nThe hire date of the user, formatted as an RFC3339 date string (e.g. `2018-01-01T01:02:03Z`)."', args=[d.arg(name='employeeHireDate', type=d.T.string)]),
      withEmployeeHireDate(employeeHireDate): { spec+: { initProvider+: { employeeHireDate: employeeHireDate } } },
      '#withEmployeeId':: d.fn(help='"The employee identifier assigned to the user by the organisation.\\nThe employee identifier assigned to the user by the organisation"', args=[d.arg(name='employeeId', type=d.T.string)]),
      withEmployeeId(employeeId): { spec+: { initProvider+: { employeeId: employeeId } } },
      '#withEmployeeType':: d.fn(help='"Captures enterprise worker type. For example, Employee, Contractor, Consultant, or Vendor.\\nCaptures enterprise worker type. For example, Employee, Contractor, Consultant, or Vendor."', args=[d.arg(name='employeeType', type=d.T.string)]),
      withEmployeeType(employeeType): { spec+: { initProvider+: { employeeType: employeeType } } },
      '#withFaxNumber':: d.fn(help='"The fax number of the user.\\nThe fax number of the user"', args=[d.arg(name='faxNumber', type=d.T.string)]),
      withFaxNumber(faxNumber): { spec+: { initProvider+: { faxNumber: faxNumber } } },
      '#withForcePasswordChange':: d.fn(help='"Whether the user is forced to change the password during the next sign-in. Only takes effect when also changing the password. Defaults to false.\\nWhether the user is forced to change the password during the next sign-in. Only takes effect when also changing the password"', args=[d.arg(name='forcePasswordChange', type=d.T.boolean)]),
      withForcePasswordChange(forcePasswordChange): { spec+: { initProvider+: { forcePasswordChange: forcePasswordChange } } },
      '#withGivenName':: d.fn(help='"The given name (first name) of the user.\\nThe given name (first name) of the user"', args=[d.arg(name='givenName', type=d.T.string)]),
      withGivenName(givenName): { spec+: { initProvider+: { givenName: givenName } } },
      '#withJobTitle':: d.fn(help='"The user’s job title.\\nThe user’s job title"', args=[d.arg(name='jobTitle', type=d.T.string)]),
      withJobTitle(jobTitle): { spec+: { initProvider+: { jobTitle: jobTitle } } },
      '#withMail':: d.fn(help='"The SMTP address for the user. This property cannot be unset once specified.\\nThe SMTP address for the user. Cannot be unset."', args=[d.arg(name='mail', type=d.T.string)]),
      withMail(mail): { spec+: { initProvider+: { mail: mail } } },
      '#withMailNickname':: d.fn(help='"The mail alias for the user. Defaults to the user name part of the user principal name (UPN).\\nThe mail alias for the user. Defaults to the user name part of the user principal name (UPN)"', args=[d.arg(name='mailNickname', type=d.T.string)]),
      withMailNickname(mailNickname): { spec+: { initProvider+: { mailNickname: mailNickname } } },
      '#withManagerId':: d.fn(help="\"The object ID of the user's manager.\\nThe object ID of the user's manager\"", args=[d.arg(name='managerId', type=d.T.string)]),
      withManagerId(managerId): { spec+: { initProvider+: { managerId: managerId } } },
      '#withMobilePhone':: d.fn(help='"The primary cellular telephone number for the user.\\nThe primary cellular telephone number for the user"', args=[d.arg(name='mobilePhone', type=d.T.string)]),
      withMobilePhone(mobilePhone): { spec+: { initProvider+: { mobilePhone: mobilePhone } } },
      '#withOfficeLocation':: d.fn(help="\"The office location in the user's place of business.\\nThe office location in the user's place of business\"", args=[d.arg(name='officeLocation', type=d.T.string)]),
      withOfficeLocation(officeLocation): { spec+: { initProvider+: { officeLocation: officeLocation } } },
      '#withOnpremisesImmutableId':: d.fn(help="\"The value used to associate an on-premise Active Directory user account with their Azure AD user object. This must be specified if you are using a federated domain for the user's user_principal_name property when creating a new user account.\\nThe value used to associate an on-premise Active Directory user account with their Azure AD user object. This must be specified if you are using a federated domain for the user's `user_principal_name` property when creating a new user account\"", args=[d.arg(name='onpremisesImmutableId', type=d.T.string)]),
      withOnpremisesImmutableId(onpremisesImmutableId): { spec+: { initProvider+: { onpremisesImmutableId: onpremisesImmutableId } } },
      '#withOtherMails':: d.fn(help='"A list of additional email addresses for the user.\\nAdditional email addresses for the user"', args=[d.arg(name='otherMails', type=d.T.array)]),
      withOtherMails(otherMails): { spec+: { initProvider+: { otherMails: if std.isArray(v=otherMails) then otherMails else [otherMails] } } },
      '#withOtherMailsMixin':: d.fn(help='"A list of additional email addresses for the user.\\nAdditional email addresses for the user"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='otherMails', type=d.T.array)]),
      withOtherMailsMixin(otherMails): { spec+: { initProvider+: { otherMails+: if std.isArray(v=otherMails) then otherMails else [otherMails] } } },
      '#withPostalCode':: d.fn(help="\"The postal code for the user's postal address. The postal code is specific to the user's country/region. In the United States of America, this attribute contains the ZIP code.\\nThe postal code for the user's postal address. The postal code is specific to the user's country/region. In the United States of America, this attribute contains the ZIP code\"", args=[d.arg(name='postalCode', type=d.T.string)]),
      withPostalCode(postalCode): { spec+: { initProvider+: { postalCode: postalCode } } },
      '#withPreferredLanguage':: d.fn(help="\"The user's preferred language, in ISO 639-1 notation.\\nThe user's preferred language, in ISO 639-1 notation\"", args=[d.arg(name='preferredLanguage', type=d.T.string)]),
      withPreferredLanguage(preferredLanguage): { spec+: { initProvider+: { preferredLanguage: preferredLanguage } } },
      '#withShowInAddressList':: d.fn(help='"Whether or not the Outlook global address list should include this user. Defaults to true.\\nWhether or not the Outlook global address list should include this user"', args=[d.arg(name='showInAddressList', type=d.T.boolean)]),
      withShowInAddressList(showInAddressList): { spec+: { initProvider+: { showInAddressList: showInAddressList } } },
      '#withState':: d.fn(help="\"The state or province in the user's address.\\nThe state or province in the user's address\"", args=[d.arg(name='state', type=d.T.string)]),
      withState(state): { spec+: { initProvider+: { state: state } } },
      '#withStreetAddress':: d.fn(help="\"The street address of the user's place of business.\\nThe street address of the user's place of business\"", args=[d.arg(name='streetAddress', type=d.T.string)]),
      withStreetAddress(streetAddress): { spec+: { initProvider+: { streetAddress: streetAddress } } },
      '#withSurname':: d.fn(help="\"The user's surname (family name or last name).\\nThe user's surname (family name or last name)\"", args=[d.arg(name='surname', type=d.T.string)]),
      withSurname(surname): { spec+: { initProvider+: { surname: surname } } },
      '#withUsageLocation':: d.fn(help='"The usage location of the user. Required for users that will be assigned licenses due to legal requirement to check for availability of services in countries. The usage location is a two letter country code (ISO standard 3166). Examples include: NO, JP, and GB. Cannot be reset to null once set.\\nThe usage location of the user. Required for users that will be assigned licenses due to legal requirement to check for availability of services in countries. The usage location is a two letter country code (ISO standard 3166). Examples include: `NO`, `JP`, and `GB`. Cannot be reset to null once set"', args=[d.arg(name='usageLocation', type=d.T.string)]),
      withUsageLocation(usageLocation): { spec+: { initProvider+: { usageLocation: usageLocation } } },
      '#withUserPrincipalName':: d.fn(help='"The user principal name (UPN) of the user.\\nThe user principal name (UPN) of the user"', args=[d.arg(name='userPrincipalName', type=d.T.string)]),
      withUserPrincipalName(userPrincipalName): { spec+: { initProvider+: { userPrincipalName: userPrincipalName } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to\\ncreate, observe, update, and delete this managed resource should be\\nconfigured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external\\nwhen this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the\\nexternal resource.\\nThis field is planned to be deprecated in favor of the ManagementPolicies\\nfield in a future release. Currently, both could be set independently and\\nnon-default values would be honored if the feature flag is enabled.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a\\nSecret to which any connection details for this managed resource should\\nbe written. Connection details frequently include the endpoint, username,\\nand password required to connect to the managed resource."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
