{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='accessPolicy', url='', help='"AccessPolicy is the Schema for the AccessPolicys API."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of AccessPolicy', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'conditionalaccess.azuread.upbound.io/v1beta2',
    kind: 'AccessPolicy',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"AccessPolicySpec defines the desired state of AccessPolicy"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#conditions':: d.obj(help='"A conditions block as documented below, which specifies the rules that must be met for the policy to apply."'),
      conditions: {
        '#applications':: d.obj(help='"An applications block as documented below, which specifies applications and user actions included in and excluded from the policy."'),
        applications: {
          '#withExcludedApplications':: d.fn(help='"A list of application IDs explicitly excluded from the policy. Can also be set to Office365."', args=[d.arg(name='excludedApplications', type=d.T.array)]),
          withExcludedApplications(excludedApplications): { spec+: { forProvider+: { conditions+: { applications+: { excludedApplications: if std.isArray(v=excludedApplications) then excludedApplications else [excludedApplications] } } } } },
          '#withExcludedApplicationsMixin':: d.fn(help='"A list of application IDs explicitly excluded from the policy. Can also be set to Office365."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedApplications', type=d.T.array)]),
          withExcludedApplicationsMixin(excludedApplications): { spec+: { forProvider+: { conditions+: { applications+: { excludedApplications+: if std.isArray(v=excludedApplications) then excludedApplications else [excludedApplications] } } } } },
          '#withIncludedApplications':: d.fn(help='"A list of application IDs the policy applies to, unless explicitly excluded (in excluded_applications). Can also be set to All, None or Office365. Cannot be specified with included_user_actions. One of included_applications or included_user_actions must be specified."', args=[d.arg(name='includedApplications', type=d.T.array)]),
          withIncludedApplications(includedApplications): { spec+: { forProvider+: { conditions+: { applications+: { includedApplications: if std.isArray(v=includedApplications) then includedApplications else [includedApplications] } } } } },
          '#withIncludedApplicationsMixin':: d.fn(help='"A list of application IDs the policy applies to, unless explicitly excluded (in excluded_applications). Can also be set to All, None or Office365. Cannot be specified with included_user_actions. One of included_applications or included_user_actions must be specified."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedApplications', type=d.T.array)]),
          withIncludedApplicationsMixin(includedApplications): { spec+: { forProvider+: { conditions+: { applications+: { includedApplications+: if std.isArray(v=includedApplications) then includedApplications else [includedApplications] } } } } },
          '#withIncludedUserActions':: d.fn(help='"A list of user actions to include. Supported values are urn:user:registerdevice and urn:user:registersecurityinfo. Cannot be specified with included_applications. One of included_applications or included_user_actions must be specified."', args=[d.arg(name='includedUserActions', type=d.T.array)]),
          withIncludedUserActions(includedUserActions): { spec+: { forProvider+: { conditions+: { applications+: { includedUserActions: if std.isArray(v=includedUserActions) then includedUserActions else [includedUserActions] } } } } },
          '#withIncludedUserActionsMixin':: d.fn(help='"A list of user actions to include. Supported values are urn:user:registerdevice and urn:user:registersecurityinfo. Cannot be specified with included_applications. One of included_applications or included_user_actions must be specified."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedUserActions', type=d.T.array)]),
          withIncludedUserActionsMixin(includedUserActions): { spec+: { forProvider+: { conditions+: { applications+: { includedUserActions+: if std.isArray(v=includedUserActions) then includedUserActions else [includedUserActions] } } } } },
        },
        '#clientApplications':: d.obj(help='"An client_applications block as documented below, which specifies service principals included in and excluded from the policy."'),
        clientApplications: {
          '#withExcludedServicePrincipals':: d.fn(help='"A list of service principal IDs explicitly excluded in the policy."', args=[d.arg(name='excludedServicePrincipals', type=d.T.array)]),
          withExcludedServicePrincipals(excludedServicePrincipals): { spec+: { forProvider+: { conditions+: { clientApplications+: { excludedServicePrincipals: if std.isArray(v=excludedServicePrincipals) then excludedServicePrincipals else [excludedServicePrincipals] } } } } },
          '#withExcludedServicePrincipalsMixin':: d.fn(help='"A list of service principal IDs explicitly excluded in the policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedServicePrincipals', type=d.T.array)]),
          withExcludedServicePrincipalsMixin(excludedServicePrincipals): { spec+: { forProvider+: { conditions+: { clientApplications+: { excludedServicePrincipals+: if std.isArray(v=excludedServicePrincipals) then excludedServicePrincipals else [excludedServicePrincipals] } } } } },
          '#withIncludedServicePrincipals':: d.fn(help='"A list of service principal IDs explicitly included in the policy. Can be set to ServicePrincipalsInMyTenant to include all service principals. This is mandatory value when at least one excluded_service_principals is set."', args=[d.arg(name='includedServicePrincipals', type=d.T.array)]),
          withIncludedServicePrincipals(includedServicePrincipals): { spec+: { forProvider+: { conditions+: { clientApplications+: { includedServicePrincipals: if std.isArray(v=includedServicePrincipals) then includedServicePrincipals else [includedServicePrincipals] } } } } },
          '#withIncludedServicePrincipalsMixin':: d.fn(help='"A list of service principal IDs explicitly included in the policy. Can be set to ServicePrincipalsInMyTenant to include all service principals. This is mandatory value when at least one excluded_service_principals is set."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedServicePrincipals', type=d.T.array)]),
          withIncludedServicePrincipalsMixin(includedServicePrincipals): { spec+: { forProvider+: { conditions+: { clientApplications+: { includedServicePrincipals+: if std.isArray(v=includedServicePrincipals) then includedServicePrincipals else [includedServicePrincipals] } } } } },
        },
        '#devices':: d.obj(help='"A devices block as documented below, which describes devices to be included in and excluded from the policy. A devices block can be added to an existing policy, but removing the devices block forces a new resource to be created."'),
        devices: {
          '#filter':: d.obj(help='"A filter block as described below."'),
          filter: {
            '#withMode':: d.fn(help='"Whether to include in, or exclude from, matching devices from the policy. Supported values are include or exclude."', args=[d.arg(name='mode', type=d.T.string)]),
            withMode(mode): { spec+: { forProvider+: { conditions+: { devices+: { filter+: { mode: mode } } } } } },
            '#withRule':: d.fn(help='"Condition filter to match devices. For more information, see official documentation."', args=[d.arg(name='rule', type=d.T.string)]),
            withRule(rule): { spec+: { forProvider+: { conditions+: { devices+: { filter+: { rule: rule } } } } } },
          },
        },
        '#locations':: d.obj(help='"A locations block as documented below, which specifies locations included in and excluded from the policy."'),
        locations: {
          '#withExcludedLocations':: d.fn(help='"A list of location IDs excluded from scope of policy. Can also be set to AllTrusted."', args=[d.arg(name='excludedLocations', type=d.T.array)]),
          withExcludedLocations(excludedLocations): { spec+: { forProvider+: { conditions+: { locations+: { excludedLocations: if std.isArray(v=excludedLocations) then excludedLocations else [excludedLocations] } } } } },
          '#withExcludedLocationsMixin':: d.fn(help='"A list of location IDs excluded from scope of policy. Can also be set to AllTrusted."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedLocations', type=d.T.array)]),
          withExcludedLocationsMixin(excludedLocations): { spec+: { forProvider+: { conditions+: { locations+: { excludedLocations+: if std.isArray(v=excludedLocations) then excludedLocations else [excludedLocations] } } } } },
          '#withIncludedLocations':: d.fn(help='"A list of location IDs in scope of policy unless explicitly excluded. Can also be set to All, or AllTrusted."', args=[d.arg(name='includedLocations', type=d.T.array)]),
          withIncludedLocations(includedLocations): { spec+: { forProvider+: { conditions+: { locations+: { includedLocations: if std.isArray(v=includedLocations) then includedLocations else [includedLocations] } } } } },
          '#withIncludedLocationsMixin':: d.fn(help='"A list of location IDs in scope of policy unless explicitly excluded. Can also be set to All, or AllTrusted."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedLocations', type=d.T.array)]),
          withIncludedLocationsMixin(includedLocations): { spec+: { forProvider+: { conditions+: { locations+: { includedLocations+: if std.isArray(v=includedLocations) then includedLocations else [includedLocations] } } } } },
        },
        '#platforms':: d.obj(help='"A platforms block as documented below, which specifies platforms included in and excluded from the policy."'),
        platforms: {
          '#withExcludedPlatforms':: d.fn(help='"A list of platforms explicitly excluded from the policy. Possible values are: all, android, iOS, linux, macOS, windows, windowsPhone or unknownFutureValue."', args=[d.arg(name='excludedPlatforms', type=d.T.array)]),
          withExcludedPlatforms(excludedPlatforms): { spec+: { forProvider+: { conditions+: { platforms+: { excludedPlatforms: if std.isArray(v=excludedPlatforms) then excludedPlatforms else [excludedPlatforms] } } } } },
          '#withExcludedPlatformsMixin':: d.fn(help='"A list of platforms explicitly excluded from the policy. Possible values are: all, android, iOS, linux, macOS, windows, windowsPhone or unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedPlatforms', type=d.T.array)]),
          withExcludedPlatformsMixin(excludedPlatforms): { spec+: { forProvider+: { conditions+: { platforms+: { excludedPlatforms+: if std.isArray(v=excludedPlatforms) then excludedPlatforms else [excludedPlatforms] } } } } },
          '#withIncludedPlatforms':: d.fn(help='"A list of platforms the policy applies to, unless explicitly excluded. Possible values are: all, android, iOS, linux, macOS, windows, windowsPhone or unknownFutureValue."', args=[d.arg(name='includedPlatforms', type=d.T.array)]),
          withIncludedPlatforms(includedPlatforms): { spec+: { forProvider+: { conditions+: { platforms+: { includedPlatforms: if std.isArray(v=includedPlatforms) then includedPlatforms else [includedPlatforms] } } } } },
          '#withIncludedPlatformsMixin':: d.fn(help='"A list of platforms the policy applies to, unless explicitly excluded. Possible values are: all, android, iOS, linux, macOS, windows, windowsPhone or unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedPlatforms', type=d.T.array)]),
          withIncludedPlatformsMixin(includedPlatforms): { spec+: { forProvider+: { conditions+: { platforms+: { includedPlatforms+: if std.isArray(v=includedPlatforms) then includedPlatforms else [includedPlatforms] } } } } },
        },
        '#users':: d.obj(help='"A users block as documented below, which specifies users, groups, and roles included in and excluded from the policy."'),
        users: {
          '#excludedGuestsOrExternalUsers':: d.obj(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users excluded from scope of policy."'),
          excludedGuestsOrExternalUsers: {
            '#externalTenants':: d.obj(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."'),
            externalTenants: {
              '#withMembers':: d.fn(help='"A list tenant IDs. Can only be specified if membership_kind is enumerated."', args=[d.arg(name='members', type=d.T.array)]),
              withMembers(members): { members: if std.isArray(v=members) then members else [members] },
              '#withMembersMixin':: d.fn(help='"A list tenant IDs. Can only be specified if membership_kind is enumerated."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='members', type=d.T.array)]),
              withMembersMixin(members): { members+: if std.isArray(v=members) then members else [members] },
              '#withMembershipKind':: d.fn(help='"The external tenant membership kind. Possible values are: all, enumerated, unknownFutureValue."', args=[d.arg(name='membershipKind', type=d.T.string)]),
              withMembershipKind(membershipKind): { membershipKind: membershipKind },
            },
            '#withExternalTenants':: d.fn(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."', args=[d.arg(name='externalTenants', type=d.T.array)]),
            withExternalTenants(externalTenants): { externalTenants: if std.isArray(v=externalTenants) then externalTenants else [externalTenants] },
            '#withExternalTenantsMixin':: d.fn(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='externalTenants', type=d.T.array)]),
            withExternalTenantsMixin(externalTenants): { externalTenants+: if std.isArray(v=externalTenants) then externalTenants else [externalTenants] },
            '#withGuestOrExternalUserTypes':: d.fn(help='"A list of guest or external user types. Possible values are: b2bCollaborationGuest, b2bCollaborationMember, b2bDirectConnectUser, internalGuest, none, otherExternalUser, serviceProvider, unknownFutureValue."', args=[d.arg(name='guestOrExternalUserTypes', type=d.T.array)]),
            withGuestOrExternalUserTypes(guestOrExternalUserTypes): { guestOrExternalUserTypes: if std.isArray(v=guestOrExternalUserTypes) then guestOrExternalUserTypes else [guestOrExternalUserTypes] },
            '#withGuestOrExternalUserTypesMixin':: d.fn(help='"A list of guest or external user types. Possible values are: b2bCollaborationGuest, b2bCollaborationMember, b2bDirectConnectUser, internalGuest, none, otherExternalUser, serviceProvider, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='guestOrExternalUserTypes', type=d.T.array)]),
            withGuestOrExternalUserTypesMixin(guestOrExternalUserTypes): { guestOrExternalUserTypes+: if std.isArray(v=guestOrExternalUserTypes) then guestOrExternalUserTypes else [guestOrExternalUserTypes] },
          },
          '#includedGuestsOrExternalUsers':: d.obj(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users in scope of policy."'),
          includedGuestsOrExternalUsers: {
            '#externalTenants':: d.obj(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."'),
            externalTenants: {
              '#withMembers':: d.fn(help='"A list tenant IDs. Can only be specified if membership_kind is enumerated."', args=[d.arg(name='members', type=d.T.array)]),
              withMembers(members): { members: if std.isArray(v=members) then members else [members] },
              '#withMembersMixin':: d.fn(help='"A list tenant IDs. Can only be specified if membership_kind is enumerated."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='members', type=d.T.array)]),
              withMembersMixin(members): { members+: if std.isArray(v=members) then members else [members] },
              '#withMembershipKind':: d.fn(help='"The external tenant membership kind. Possible values are: all, enumerated, unknownFutureValue."', args=[d.arg(name='membershipKind', type=d.T.string)]),
              withMembershipKind(membershipKind): { membershipKind: membershipKind },
            },
            '#withExternalTenants':: d.fn(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."', args=[d.arg(name='externalTenants', type=d.T.array)]),
            withExternalTenants(externalTenants): { externalTenants: if std.isArray(v=externalTenants) then externalTenants else [externalTenants] },
            '#withExternalTenantsMixin':: d.fn(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='externalTenants', type=d.T.array)]),
            withExternalTenantsMixin(externalTenants): { externalTenants+: if std.isArray(v=externalTenants) then externalTenants else [externalTenants] },
            '#withGuestOrExternalUserTypes':: d.fn(help='"A list of guest or external user types. Possible values are: b2bCollaborationGuest, b2bCollaborationMember, b2bDirectConnectUser, internalGuest, none, otherExternalUser, serviceProvider, unknownFutureValue."', args=[d.arg(name='guestOrExternalUserTypes', type=d.T.array)]),
            withGuestOrExternalUserTypes(guestOrExternalUserTypes): { guestOrExternalUserTypes: if std.isArray(v=guestOrExternalUserTypes) then guestOrExternalUserTypes else [guestOrExternalUserTypes] },
            '#withGuestOrExternalUserTypesMixin':: d.fn(help='"A list of guest or external user types. Possible values are: b2bCollaborationGuest, b2bCollaborationMember, b2bDirectConnectUser, internalGuest, none, otherExternalUser, serviceProvider, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='guestOrExternalUserTypes', type=d.T.array)]),
            withGuestOrExternalUserTypesMixin(guestOrExternalUserTypes): { guestOrExternalUserTypes+: if std.isArray(v=guestOrExternalUserTypes) then guestOrExternalUserTypes else [guestOrExternalUserTypes] },
          },
          '#withExcludedGroups':: d.fn(help='"A list of group IDs excluded from scope of policy."', args=[d.arg(name='excludedGroups', type=d.T.array)]),
          withExcludedGroups(excludedGroups): { spec+: { forProvider+: { conditions+: { users+: { excludedGroups: if std.isArray(v=excludedGroups) then excludedGroups else [excludedGroups] } } } } },
          '#withExcludedGroupsMixin':: d.fn(help='"A list of group IDs excluded from scope of policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedGroups', type=d.T.array)]),
          withExcludedGroupsMixin(excludedGroups): { spec+: { forProvider+: { conditions+: { users+: { excludedGroups+: if std.isArray(v=excludedGroups) then excludedGroups else [excludedGroups] } } } } },
          '#withExcludedGuestsOrExternalUsers':: d.fn(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users excluded from scope of policy."', args=[d.arg(name='excludedGuestsOrExternalUsers', type=d.T.array)]),
          withExcludedGuestsOrExternalUsers(excludedGuestsOrExternalUsers): { spec+: { forProvider+: { conditions+: { users+: { excludedGuestsOrExternalUsers: if std.isArray(v=excludedGuestsOrExternalUsers) then excludedGuestsOrExternalUsers else [excludedGuestsOrExternalUsers] } } } } },
          '#withExcludedGuestsOrExternalUsersMixin':: d.fn(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users excluded from scope of policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedGuestsOrExternalUsers', type=d.T.array)]),
          withExcludedGuestsOrExternalUsersMixin(excludedGuestsOrExternalUsers): { spec+: { forProvider+: { conditions+: { users+: { excludedGuestsOrExternalUsers+: if std.isArray(v=excludedGuestsOrExternalUsers) then excludedGuestsOrExternalUsers else [excludedGuestsOrExternalUsers] } } } } },
          '#withExcludedRoles':: d.fn(help='"A list of role IDs excluded from scope of policy."', args=[d.arg(name='excludedRoles', type=d.T.array)]),
          withExcludedRoles(excludedRoles): { spec+: { forProvider+: { conditions+: { users+: { excludedRoles: if std.isArray(v=excludedRoles) then excludedRoles else [excludedRoles] } } } } },
          '#withExcludedRolesMixin':: d.fn(help='"A list of role IDs excluded from scope of policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedRoles', type=d.T.array)]),
          withExcludedRolesMixin(excludedRoles): { spec+: { forProvider+: { conditions+: { users+: { excludedRoles+: if std.isArray(v=excludedRoles) then excludedRoles else [excludedRoles] } } } } },
          '#withExcludedUsers':: d.fn(help='"A list of user IDs excluded from scope of policy and/or GuestsOrExternalUsers."', args=[d.arg(name='excludedUsers', type=d.T.array)]),
          withExcludedUsers(excludedUsers): { spec+: { forProvider+: { conditions+: { users+: { excludedUsers: if std.isArray(v=excludedUsers) then excludedUsers else [excludedUsers] } } } } },
          '#withExcludedUsersMixin':: d.fn(help='"A list of user IDs excluded from scope of policy and/or GuestsOrExternalUsers."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedUsers', type=d.T.array)]),
          withExcludedUsersMixin(excludedUsers): { spec+: { forProvider+: { conditions+: { users+: { excludedUsers+: if std.isArray(v=excludedUsers) then excludedUsers else [excludedUsers] } } } } },
          '#withIncludedGroups':: d.fn(help='"A list of group IDs in scope of policy unless explicitly excluded."', args=[d.arg(name='includedGroups', type=d.T.array)]),
          withIncludedGroups(includedGroups): { spec+: { forProvider+: { conditions+: { users+: { includedGroups: if std.isArray(v=includedGroups) then includedGroups else [includedGroups] } } } } },
          '#withIncludedGroupsMixin':: d.fn(help='"A list of group IDs in scope of policy unless explicitly excluded."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedGroups', type=d.T.array)]),
          withIncludedGroupsMixin(includedGroups): { spec+: { forProvider+: { conditions+: { users+: { includedGroups+: if std.isArray(v=includedGroups) then includedGroups else [includedGroups] } } } } },
          '#withIncludedGuestsOrExternalUsers':: d.fn(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users in scope of policy."', args=[d.arg(name='includedGuestsOrExternalUsers', type=d.T.array)]),
          withIncludedGuestsOrExternalUsers(includedGuestsOrExternalUsers): { spec+: { forProvider+: { conditions+: { users+: { includedGuestsOrExternalUsers: if std.isArray(v=includedGuestsOrExternalUsers) then includedGuestsOrExternalUsers else [includedGuestsOrExternalUsers] } } } } },
          '#withIncludedGuestsOrExternalUsersMixin':: d.fn(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users in scope of policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedGuestsOrExternalUsers', type=d.T.array)]),
          withIncludedGuestsOrExternalUsersMixin(includedGuestsOrExternalUsers): { spec+: { forProvider+: { conditions+: { users+: { includedGuestsOrExternalUsers+: if std.isArray(v=includedGuestsOrExternalUsers) then includedGuestsOrExternalUsers else [includedGuestsOrExternalUsers] } } } } },
          '#withIncludedRoles':: d.fn(help='"A list of role IDs in scope of policy unless explicitly excluded."', args=[d.arg(name='includedRoles', type=d.T.array)]),
          withIncludedRoles(includedRoles): { spec+: { forProvider+: { conditions+: { users+: { includedRoles: if std.isArray(v=includedRoles) then includedRoles else [includedRoles] } } } } },
          '#withIncludedRolesMixin':: d.fn(help='"A list of role IDs in scope of policy unless explicitly excluded."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedRoles', type=d.T.array)]),
          withIncludedRolesMixin(includedRoles): { spec+: { forProvider+: { conditions+: { users+: { includedRoles+: if std.isArray(v=includedRoles) then includedRoles else [includedRoles] } } } } },
          '#withIncludedUsers':: d.fn(help='"A list of user IDs in scope of policy unless explicitly excluded, or None or All or GuestsOrExternalUsers."', args=[d.arg(name='includedUsers', type=d.T.array)]),
          withIncludedUsers(includedUsers): { spec+: { forProvider+: { conditions+: { users+: { includedUsers: if std.isArray(v=includedUsers) then includedUsers else [includedUsers] } } } } },
          '#withIncludedUsersMixin':: d.fn(help='"A list of user IDs in scope of policy unless explicitly excluded, or None or All or GuestsOrExternalUsers."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedUsers', type=d.T.array)]),
          withIncludedUsersMixin(includedUsers): { spec+: { forProvider+: { conditions+: { users+: { includedUsers+: if std.isArray(v=includedUsers) then includedUsers else [includedUsers] } } } } },
        },
        '#withClientAppTypes':: d.fn(help='"A list of client application types included in the policy. Possible values are: all, browser, mobileAppsAndDesktopClients, exchangeActiveSync, easSupported and other."', args=[d.arg(name='clientAppTypes', type=d.T.array)]),
        withClientAppTypes(clientAppTypes): { spec+: { forProvider+: { conditions+: { clientAppTypes: if std.isArray(v=clientAppTypes) then clientAppTypes else [clientAppTypes] } } } },
        '#withClientAppTypesMixin':: d.fn(help='"A list of client application types included in the policy. Possible values are: all, browser, mobileAppsAndDesktopClients, exchangeActiveSync, easSupported and other."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='clientAppTypes', type=d.T.array)]),
        withClientAppTypesMixin(clientAppTypes): { spec+: { forProvider+: { conditions+: { clientAppTypes+: if std.isArray(v=clientAppTypes) then clientAppTypes else [clientAppTypes] } } } },
        '#withInsiderRiskLevels':: d.fn(help='"The insider risk level in the policy. Possible values are: minor, moderate, elevated, unknownFutureValue."', args=[d.arg(name='insiderRiskLevels', type=d.T.string)]),
        withInsiderRiskLevels(insiderRiskLevels): { spec+: { forProvider+: { conditions+: { insiderRiskLevels: insiderRiskLevels } } } },
        '#withServicePrincipalRiskLevels':: d.fn(help='"A list of service principal sign-in risk levels included in the policy. Possible values are: low, medium, high, none, unknownFutureValue."', args=[d.arg(name='servicePrincipalRiskLevels', type=d.T.array)]),
        withServicePrincipalRiskLevels(servicePrincipalRiskLevels): { spec+: { forProvider+: { conditions+: { servicePrincipalRiskLevels: if std.isArray(v=servicePrincipalRiskLevels) then servicePrincipalRiskLevels else [servicePrincipalRiskLevels] } } } },
        '#withServicePrincipalRiskLevelsMixin':: d.fn(help='"A list of service principal sign-in risk levels included in the policy. Possible values are: low, medium, high, none, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='servicePrincipalRiskLevels', type=d.T.array)]),
        withServicePrincipalRiskLevelsMixin(servicePrincipalRiskLevels): { spec+: { forProvider+: { conditions+: { servicePrincipalRiskLevels+: if std.isArray(v=servicePrincipalRiskLevels) then servicePrincipalRiskLevels else [servicePrincipalRiskLevels] } } } },
        '#withSignInRiskLevels':: d.fn(help='"A list of user sign-in risk levels included in the policy. Possible values are: low, medium, high, hidden, none, unknownFutureValue."', args=[d.arg(name='signInRiskLevels', type=d.T.array)]),
        withSignInRiskLevels(signInRiskLevels): { spec+: { forProvider+: { conditions+: { signInRiskLevels: if std.isArray(v=signInRiskLevels) then signInRiskLevels else [signInRiskLevels] } } } },
        '#withSignInRiskLevelsMixin':: d.fn(help='"A list of user sign-in risk levels included in the policy. Possible values are: low, medium, high, hidden, none, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='signInRiskLevels', type=d.T.array)]),
        withSignInRiskLevelsMixin(signInRiskLevels): { spec+: { forProvider+: { conditions+: { signInRiskLevels+: if std.isArray(v=signInRiskLevels) then signInRiskLevels else [signInRiskLevels] } } } },
        '#withUserRiskLevels':: d.fn(help='"A list of user risk levels included in the policy. Possible values are: low, medium, high, hidden, none, unknownFutureValue."', args=[d.arg(name='userRiskLevels', type=d.T.array)]),
        withUserRiskLevels(userRiskLevels): { spec+: { forProvider+: { conditions+: { userRiskLevels: if std.isArray(v=userRiskLevels) then userRiskLevels else [userRiskLevels] } } } },
        '#withUserRiskLevelsMixin':: d.fn(help='"A list of user risk levels included in the policy. Possible values are: low, medium, high, hidden, none, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='userRiskLevels', type=d.T.array)]),
        withUserRiskLevelsMixin(userRiskLevels): { spec+: { forProvider+: { conditions+: { userRiskLevels+: if std.isArray(v=userRiskLevels) then userRiskLevels else [userRiskLevels] } } } },
      },
      '#grantControls':: d.obj(help='"A grant_controls block as documented below, which specifies the grant controls that must be fulfilled to pass the policy."'),
      grantControls: {
        '#withAuthenticationStrengthPolicyId':: d.fn(help='"ID of an Authentication Strength Policy to use in this policy. When using a hard-coded ID, the UUID value should be prefixed with: /policies/authenticationStrengthPolicies/."', args=[d.arg(name='authenticationStrengthPolicyId', type=d.T.string)]),
        withAuthenticationStrengthPolicyId(authenticationStrengthPolicyId): { spec+: { forProvider+: { grantControls+: { authenticationStrengthPolicyId: authenticationStrengthPolicyId } } } },
        '#withBuiltInControls':: d.fn(help='"List of built-in controls required by the policy. Possible values are: block, mfa, approvedApplication, compliantApplication, compliantDevice, domainJoinedDevice, passwordChange or unknownFutureValue."', args=[d.arg(name='builtInControls', type=d.T.array)]),
        withBuiltInControls(builtInControls): { spec+: { forProvider+: { grantControls+: { builtInControls: if std.isArray(v=builtInControls) then builtInControls else [builtInControls] } } } },
        '#withBuiltInControlsMixin':: d.fn(help='"List of built-in controls required by the policy. Possible values are: block, mfa, approvedApplication, compliantApplication, compliantDevice, domainJoinedDevice, passwordChange or unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='builtInControls', type=d.T.array)]),
        withBuiltInControlsMixin(builtInControls): { spec+: { forProvider+: { grantControls+: { builtInControls+: if std.isArray(v=builtInControls) then builtInControls else [builtInControls] } } } },
        '#withCustomAuthenticationFactors':: d.fn(help='"List of custom controls IDs required by the policy."', args=[d.arg(name='customAuthenticationFactors', type=d.T.array)]),
        withCustomAuthenticationFactors(customAuthenticationFactors): { spec+: { forProvider+: { grantControls+: { customAuthenticationFactors: if std.isArray(v=customAuthenticationFactors) then customAuthenticationFactors else [customAuthenticationFactors] } } } },
        '#withCustomAuthenticationFactorsMixin':: d.fn(help='"List of custom controls IDs required by the policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='customAuthenticationFactors', type=d.T.array)]),
        withCustomAuthenticationFactorsMixin(customAuthenticationFactors): { spec+: { forProvider+: { grantControls+: { customAuthenticationFactors+: if std.isArray(v=customAuthenticationFactors) then customAuthenticationFactors else [customAuthenticationFactors] } } } },
        '#withOperator':: d.fn(help='"Defines the relationship of the grant controls. Possible values are: AND, OR."', args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { spec+: { forProvider+: { grantControls+: { operator: operator } } } },
        '#withTermsOfUse':: d.fn(help='"List of terms of use IDs required by the policy."', args=[d.arg(name='termsOfUse', type=d.T.array)]),
        withTermsOfUse(termsOfUse): { spec+: { forProvider+: { grantControls+: { termsOfUse: if std.isArray(v=termsOfUse) then termsOfUse else [termsOfUse] } } } },
        '#withTermsOfUseMixin':: d.fn(help='"List of terms of use IDs required by the policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='termsOfUse', type=d.T.array)]),
        withTermsOfUseMixin(termsOfUse): { spec+: { forProvider+: { grantControls+: { termsOfUse+: if std.isArray(v=termsOfUse) then termsOfUse else [termsOfUse] } } } },
      },
      '#sessionControls':: d.obj(help='"A session_controls block as documented below, which specifies the session controls that are enforced after sign-in."'),
      sessionControls: {
        '#withApplicationEnforcedRestrictionsEnabled':: d.fn(help='"Whether application enforced restrictions are enabled. Defaults to false."', args=[d.arg(name='applicationEnforcedRestrictionsEnabled', type=d.T.boolean)]),
        withApplicationEnforcedRestrictionsEnabled(applicationEnforcedRestrictionsEnabled): { spec+: { forProvider+: { sessionControls+: { applicationEnforcedRestrictionsEnabled: applicationEnforcedRestrictionsEnabled } } } },
        '#withCloudAppSecurityPolicy':: d.fn(help='"Enables cloud app security and specifies the cloud app security policy to use. Possible values are: blockDownloads, mcasConfigured, monitorOnly or unknownFutureValue."', args=[d.arg(name='cloudAppSecurityPolicy', type=d.T.string)]),
        withCloudAppSecurityPolicy(cloudAppSecurityPolicy): { spec+: { forProvider+: { sessionControls+: { cloudAppSecurityPolicy: cloudAppSecurityPolicy } } } },
        '#withDisableResilienceDefaults':: d.fn(help='"Disables resilience defaults. Defaults to false."', args=[d.arg(name='disableResilienceDefaults', type=d.T.boolean)]),
        withDisableResilienceDefaults(disableResilienceDefaults): { spec+: { forProvider+: { sessionControls+: { disableResilienceDefaults: disableResilienceDefaults } } } },
        '#withPersistentBrowserMode':: d.fn(help='"Session control to define whether to persist cookies. Possible values are: always or never."', args=[d.arg(name='persistentBrowserMode', type=d.T.string)]),
        withPersistentBrowserMode(persistentBrowserMode): { spec+: { forProvider+: { sessionControls+: { persistentBrowserMode: persistentBrowserMode } } } },
        '#withSignInFrequency':: d.fn(help='"Number of days or hours to enforce sign-in frequency. Required when sign_in_frequency_period is specified."', args=[d.arg(name='signInFrequency', type=d.T.number)]),
        withSignInFrequency(signInFrequency): { spec+: { forProvider+: { sessionControls+: { signInFrequency: signInFrequency } } } },
        '#withSignInFrequencyAuthenticationType':: d.fn(help='"Authentication type for enforcing sign-in frequency. Possible values are: primaryAndSecondaryAuthentication or secondaryAuthentication. Defaults to primaryAndSecondaryAuthentication."', args=[d.arg(name='signInFrequencyAuthenticationType', type=d.T.string)]),
        withSignInFrequencyAuthenticationType(signInFrequencyAuthenticationType): { spec+: { forProvider+: { sessionControls+: { signInFrequencyAuthenticationType: signInFrequencyAuthenticationType } } } },
        '#withSignInFrequencyInterval':: d.fn(help='"The interval to apply to sign-in frequency control. Possible values are: timeBased or everyTime. Defaults to timeBased."', args=[d.arg(name='signInFrequencyInterval', type=d.T.string)]),
        withSignInFrequencyInterval(signInFrequencyInterval): { spec+: { forProvider+: { sessionControls+: { signInFrequencyInterval: signInFrequencyInterval } } } },
        '#withSignInFrequencyPeriod':: d.fn(help='"The time period to enforce sign-in frequency. Possible values are: hours or days. Required when sign_in_frequency_period is specified."', args=[d.arg(name='signInFrequencyPeriod', type=d.T.string)]),
        withSignInFrequencyPeriod(signInFrequencyPeriod): { spec+: { forProvider+: { sessionControls+: { signInFrequencyPeriod: signInFrequencyPeriod } } } },
      },
      '#withDisplayName':: d.fn(help='"The friendly name for this Conditional Access Policy."', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { forProvider+: { displayName: displayName } } },
      '#withState':: d.fn(help='"Specifies the state of the policy object. Possible values are: enabled, disabled and enabledForReportingButNotEnforced"', args=[d.arg(name='state', type=d.T.string)]),
      withState(state): { spec+: { forProvider+: { state: state } } },
    },
    '#initProvider':: d.obj(help='"THIS IS A BETA FIELD. It will be honored\\nunless the Management Policies feature flag is disabled.\\nInitProvider holds the same fields as ForProvider, with the exception\\nof Identifier and other resource reference fields. The fields that are\\nin InitProvider are merged into ForProvider when the resource is created.\\nThe same fields are also added to the terraform ignore_changes hook, to\\navoid updating them after creation. This is useful for fields that are\\nrequired on creation, but we do not desire to update them after creation,\\nfor example because of an external controller is managing them, like an\\nautoscaler."'),
    initProvider: {
      '#conditions':: d.obj(help='"A conditions block as documented below, which specifies the rules that must be met for the policy to apply."'),
      conditions: {
        '#applications':: d.obj(help='"An applications block as documented below, which specifies applications and user actions included in and excluded from the policy."'),
        applications: {
          '#withExcludedApplications':: d.fn(help='"A list of application IDs explicitly excluded from the policy. Can also be set to Office365."', args=[d.arg(name='excludedApplications', type=d.T.array)]),
          withExcludedApplications(excludedApplications): { spec+: { initProvider+: { conditions+: { applications+: { excludedApplications: if std.isArray(v=excludedApplications) then excludedApplications else [excludedApplications] } } } } },
          '#withExcludedApplicationsMixin':: d.fn(help='"A list of application IDs explicitly excluded from the policy. Can also be set to Office365."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedApplications', type=d.T.array)]),
          withExcludedApplicationsMixin(excludedApplications): { spec+: { initProvider+: { conditions+: { applications+: { excludedApplications+: if std.isArray(v=excludedApplications) then excludedApplications else [excludedApplications] } } } } },
          '#withIncludedApplications':: d.fn(help='"A list of application IDs the policy applies to, unless explicitly excluded (in excluded_applications). Can also be set to All, None or Office365. Cannot be specified with included_user_actions. One of included_applications or included_user_actions must be specified."', args=[d.arg(name='includedApplications', type=d.T.array)]),
          withIncludedApplications(includedApplications): { spec+: { initProvider+: { conditions+: { applications+: { includedApplications: if std.isArray(v=includedApplications) then includedApplications else [includedApplications] } } } } },
          '#withIncludedApplicationsMixin':: d.fn(help='"A list of application IDs the policy applies to, unless explicitly excluded (in excluded_applications). Can also be set to All, None or Office365. Cannot be specified with included_user_actions. One of included_applications or included_user_actions must be specified."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedApplications', type=d.T.array)]),
          withIncludedApplicationsMixin(includedApplications): { spec+: { initProvider+: { conditions+: { applications+: { includedApplications+: if std.isArray(v=includedApplications) then includedApplications else [includedApplications] } } } } },
          '#withIncludedUserActions':: d.fn(help='"A list of user actions to include. Supported values are urn:user:registerdevice and urn:user:registersecurityinfo. Cannot be specified with included_applications. One of included_applications or included_user_actions must be specified."', args=[d.arg(name='includedUserActions', type=d.T.array)]),
          withIncludedUserActions(includedUserActions): { spec+: { initProvider+: { conditions+: { applications+: { includedUserActions: if std.isArray(v=includedUserActions) then includedUserActions else [includedUserActions] } } } } },
          '#withIncludedUserActionsMixin':: d.fn(help='"A list of user actions to include. Supported values are urn:user:registerdevice and urn:user:registersecurityinfo. Cannot be specified with included_applications. One of included_applications or included_user_actions must be specified."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedUserActions', type=d.T.array)]),
          withIncludedUserActionsMixin(includedUserActions): { spec+: { initProvider+: { conditions+: { applications+: { includedUserActions+: if std.isArray(v=includedUserActions) then includedUserActions else [includedUserActions] } } } } },
        },
        '#clientApplications':: d.obj(help='"An client_applications block as documented below, which specifies service principals included in and excluded from the policy."'),
        clientApplications: {
          '#withExcludedServicePrincipals':: d.fn(help='"A list of service principal IDs explicitly excluded in the policy."', args=[d.arg(name='excludedServicePrincipals', type=d.T.array)]),
          withExcludedServicePrincipals(excludedServicePrincipals): { spec+: { initProvider+: { conditions+: { clientApplications+: { excludedServicePrincipals: if std.isArray(v=excludedServicePrincipals) then excludedServicePrincipals else [excludedServicePrincipals] } } } } },
          '#withExcludedServicePrincipalsMixin':: d.fn(help='"A list of service principal IDs explicitly excluded in the policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedServicePrincipals', type=d.T.array)]),
          withExcludedServicePrincipalsMixin(excludedServicePrincipals): { spec+: { initProvider+: { conditions+: { clientApplications+: { excludedServicePrincipals+: if std.isArray(v=excludedServicePrincipals) then excludedServicePrincipals else [excludedServicePrincipals] } } } } },
          '#withIncludedServicePrincipals':: d.fn(help='"A list of service principal IDs explicitly included in the policy. Can be set to ServicePrincipalsInMyTenant to include all service principals. This is mandatory value when at least one excluded_service_principals is set."', args=[d.arg(name='includedServicePrincipals', type=d.T.array)]),
          withIncludedServicePrincipals(includedServicePrincipals): { spec+: { initProvider+: { conditions+: { clientApplications+: { includedServicePrincipals: if std.isArray(v=includedServicePrincipals) then includedServicePrincipals else [includedServicePrincipals] } } } } },
          '#withIncludedServicePrincipalsMixin':: d.fn(help='"A list of service principal IDs explicitly included in the policy. Can be set to ServicePrincipalsInMyTenant to include all service principals. This is mandatory value when at least one excluded_service_principals is set."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedServicePrincipals', type=d.T.array)]),
          withIncludedServicePrincipalsMixin(includedServicePrincipals): { spec+: { initProvider+: { conditions+: { clientApplications+: { includedServicePrincipals+: if std.isArray(v=includedServicePrincipals) then includedServicePrincipals else [includedServicePrincipals] } } } } },
        },
        '#devices':: d.obj(help='"A devices block as documented below, which describes devices to be included in and excluded from the policy. A devices block can be added to an existing policy, but removing the devices block forces a new resource to be created."'),
        devices: {
          '#filter':: d.obj(help='"A filter block as described below."'),
          filter: {
            '#withMode':: d.fn(help='"Whether to include in, or exclude from, matching devices from the policy. Supported values are include or exclude."', args=[d.arg(name='mode', type=d.T.string)]),
            withMode(mode): { spec+: { initProvider+: { conditions+: { devices+: { filter+: { mode: mode } } } } } },
            '#withRule':: d.fn(help='"Condition filter to match devices. For more information, see official documentation."', args=[d.arg(name='rule', type=d.T.string)]),
            withRule(rule): { spec+: { initProvider+: { conditions+: { devices+: { filter+: { rule: rule } } } } } },
          },
        },
        '#locations':: d.obj(help='"A locations block as documented below, which specifies locations included in and excluded from the policy."'),
        locations: {
          '#withExcludedLocations':: d.fn(help='"A list of location IDs excluded from scope of policy. Can also be set to AllTrusted."', args=[d.arg(name='excludedLocations', type=d.T.array)]),
          withExcludedLocations(excludedLocations): { spec+: { initProvider+: { conditions+: { locations+: { excludedLocations: if std.isArray(v=excludedLocations) then excludedLocations else [excludedLocations] } } } } },
          '#withExcludedLocationsMixin':: d.fn(help='"A list of location IDs excluded from scope of policy. Can also be set to AllTrusted."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedLocations', type=d.T.array)]),
          withExcludedLocationsMixin(excludedLocations): { spec+: { initProvider+: { conditions+: { locations+: { excludedLocations+: if std.isArray(v=excludedLocations) then excludedLocations else [excludedLocations] } } } } },
          '#withIncludedLocations':: d.fn(help='"A list of location IDs in scope of policy unless explicitly excluded. Can also be set to All, or AllTrusted."', args=[d.arg(name='includedLocations', type=d.T.array)]),
          withIncludedLocations(includedLocations): { spec+: { initProvider+: { conditions+: { locations+: { includedLocations: if std.isArray(v=includedLocations) then includedLocations else [includedLocations] } } } } },
          '#withIncludedLocationsMixin':: d.fn(help='"A list of location IDs in scope of policy unless explicitly excluded. Can also be set to All, or AllTrusted."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedLocations', type=d.T.array)]),
          withIncludedLocationsMixin(includedLocations): { spec+: { initProvider+: { conditions+: { locations+: { includedLocations+: if std.isArray(v=includedLocations) then includedLocations else [includedLocations] } } } } },
        },
        '#platforms':: d.obj(help='"A platforms block as documented below, which specifies platforms included in and excluded from the policy."'),
        platforms: {
          '#withExcludedPlatforms':: d.fn(help='"A list of platforms explicitly excluded from the policy. Possible values are: all, android, iOS, linux, macOS, windows, windowsPhone or unknownFutureValue."', args=[d.arg(name='excludedPlatforms', type=d.T.array)]),
          withExcludedPlatforms(excludedPlatforms): { spec+: { initProvider+: { conditions+: { platforms+: { excludedPlatforms: if std.isArray(v=excludedPlatforms) then excludedPlatforms else [excludedPlatforms] } } } } },
          '#withExcludedPlatformsMixin':: d.fn(help='"A list of platforms explicitly excluded from the policy. Possible values are: all, android, iOS, linux, macOS, windows, windowsPhone or unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedPlatforms', type=d.T.array)]),
          withExcludedPlatformsMixin(excludedPlatforms): { spec+: { initProvider+: { conditions+: { platforms+: { excludedPlatforms+: if std.isArray(v=excludedPlatforms) then excludedPlatforms else [excludedPlatforms] } } } } },
          '#withIncludedPlatforms':: d.fn(help='"A list of platforms the policy applies to, unless explicitly excluded. Possible values are: all, android, iOS, linux, macOS, windows, windowsPhone or unknownFutureValue."', args=[d.arg(name='includedPlatforms', type=d.T.array)]),
          withIncludedPlatforms(includedPlatforms): { spec+: { initProvider+: { conditions+: { platforms+: { includedPlatforms: if std.isArray(v=includedPlatforms) then includedPlatforms else [includedPlatforms] } } } } },
          '#withIncludedPlatformsMixin':: d.fn(help='"A list of platforms the policy applies to, unless explicitly excluded. Possible values are: all, android, iOS, linux, macOS, windows, windowsPhone or unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedPlatforms', type=d.T.array)]),
          withIncludedPlatformsMixin(includedPlatforms): { spec+: { initProvider+: { conditions+: { platforms+: { includedPlatforms+: if std.isArray(v=includedPlatforms) then includedPlatforms else [includedPlatforms] } } } } },
        },
        '#users':: d.obj(help='"A users block as documented below, which specifies users, groups, and roles included in and excluded from the policy."'),
        users: {
          '#excludedGuestsOrExternalUsers':: d.obj(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users excluded from scope of policy."'),
          excludedGuestsOrExternalUsers: {
            '#externalTenants':: d.obj(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."'),
            externalTenants: {
              '#withMembers':: d.fn(help='"A list tenant IDs. Can only be specified if membership_kind is enumerated."', args=[d.arg(name='members', type=d.T.array)]),
              withMembers(members): { members: if std.isArray(v=members) then members else [members] },
              '#withMembersMixin':: d.fn(help='"A list tenant IDs. Can only be specified if membership_kind is enumerated."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='members', type=d.T.array)]),
              withMembersMixin(members): { members+: if std.isArray(v=members) then members else [members] },
              '#withMembershipKind':: d.fn(help='"The external tenant membership kind. Possible values are: all, enumerated, unknownFutureValue."', args=[d.arg(name='membershipKind', type=d.T.string)]),
              withMembershipKind(membershipKind): { membershipKind: membershipKind },
            },
            '#withExternalTenants':: d.fn(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."', args=[d.arg(name='externalTenants', type=d.T.array)]),
            withExternalTenants(externalTenants): { externalTenants: if std.isArray(v=externalTenants) then externalTenants else [externalTenants] },
            '#withExternalTenantsMixin':: d.fn(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='externalTenants', type=d.T.array)]),
            withExternalTenantsMixin(externalTenants): { externalTenants+: if std.isArray(v=externalTenants) then externalTenants else [externalTenants] },
            '#withGuestOrExternalUserTypes':: d.fn(help='"A list of guest or external user types. Possible values are: b2bCollaborationGuest, b2bCollaborationMember, b2bDirectConnectUser, internalGuest, none, otherExternalUser, serviceProvider, unknownFutureValue."', args=[d.arg(name='guestOrExternalUserTypes', type=d.T.array)]),
            withGuestOrExternalUserTypes(guestOrExternalUserTypes): { guestOrExternalUserTypes: if std.isArray(v=guestOrExternalUserTypes) then guestOrExternalUserTypes else [guestOrExternalUserTypes] },
            '#withGuestOrExternalUserTypesMixin':: d.fn(help='"A list of guest or external user types. Possible values are: b2bCollaborationGuest, b2bCollaborationMember, b2bDirectConnectUser, internalGuest, none, otherExternalUser, serviceProvider, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='guestOrExternalUserTypes', type=d.T.array)]),
            withGuestOrExternalUserTypesMixin(guestOrExternalUserTypes): { guestOrExternalUserTypes+: if std.isArray(v=guestOrExternalUserTypes) then guestOrExternalUserTypes else [guestOrExternalUserTypes] },
          },
          '#includedGuestsOrExternalUsers':: d.obj(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users in scope of policy."'),
          includedGuestsOrExternalUsers: {
            '#externalTenants':: d.obj(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."'),
            externalTenants: {
              '#withMembers':: d.fn(help='"A list tenant IDs. Can only be specified if membership_kind is enumerated."', args=[d.arg(name='members', type=d.T.array)]),
              withMembers(members): { members: if std.isArray(v=members) then members else [members] },
              '#withMembersMixin':: d.fn(help='"A list tenant IDs. Can only be specified if membership_kind is enumerated."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='members', type=d.T.array)]),
              withMembersMixin(members): { members+: if std.isArray(v=members) then members else [members] },
              '#withMembershipKind':: d.fn(help='"The external tenant membership kind. Possible values are: all, enumerated, unknownFutureValue."', args=[d.arg(name='membershipKind', type=d.T.string)]),
              withMembershipKind(membershipKind): { membershipKind: membershipKind },
            },
            '#withExternalTenants':: d.fn(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."', args=[d.arg(name='externalTenants', type=d.T.array)]),
            withExternalTenants(externalTenants): { externalTenants: if std.isArray(v=externalTenants) then externalTenants else [externalTenants] },
            '#withExternalTenantsMixin':: d.fn(help='"An external_tenants block as documented below, which specifies external tenants in a policy scope."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='externalTenants', type=d.T.array)]),
            withExternalTenantsMixin(externalTenants): { externalTenants+: if std.isArray(v=externalTenants) then externalTenants else [externalTenants] },
            '#withGuestOrExternalUserTypes':: d.fn(help='"A list of guest or external user types. Possible values are: b2bCollaborationGuest, b2bCollaborationMember, b2bDirectConnectUser, internalGuest, none, otherExternalUser, serviceProvider, unknownFutureValue."', args=[d.arg(name='guestOrExternalUserTypes', type=d.T.array)]),
            withGuestOrExternalUserTypes(guestOrExternalUserTypes): { guestOrExternalUserTypes: if std.isArray(v=guestOrExternalUserTypes) then guestOrExternalUserTypes else [guestOrExternalUserTypes] },
            '#withGuestOrExternalUserTypesMixin':: d.fn(help='"A list of guest or external user types. Possible values are: b2bCollaborationGuest, b2bCollaborationMember, b2bDirectConnectUser, internalGuest, none, otherExternalUser, serviceProvider, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='guestOrExternalUserTypes', type=d.T.array)]),
            withGuestOrExternalUserTypesMixin(guestOrExternalUserTypes): { guestOrExternalUserTypes+: if std.isArray(v=guestOrExternalUserTypes) then guestOrExternalUserTypes else [guestOrExternalUserTypes] },
          },
          '#withExcludedGroups':: d.fn(help='"A list of group IDs excluded from scope of policy."', args=[d.arg(name='excludedGroups', type=d.T.array)]),
          withExcludedGroups(excludedGroups): { spec+: { initProvider+: { conditions+: { users+: { excludedGroups: if std.isArray(v=excludedGroups) then excludedGroups else [excludedGroups] } } } } },
          '#withExcludedGroupsMixin':: d.fn(help='"A list of group IDs excluded from scope of policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedGroups', type=d.T.array)]),
          withExcludedGroupsMixin(excludedGroups): { spec+: { initProvider+: { conditions+: { users+: { excludedGroups+: if std.isArray(v=excludedGroups) then excludedGroups else [excludedGroups] } } } } },
          '#withExcludedGuestsOrExternalUsers':: d.fn(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users excluded from scope of policy."', args=[d.arg(name='excludedGuestsOrExternalUsers', type=d.T.array)]),
          withExcludedGuestsOrExternalUsers(excludedGuestsOrExternalUsers): { spec+: { initProvider+: { conditions+: { users+: { excludedGuestsOrExternalUsers: if std.isArray(v=excludedGuestsOrExternalUsers) then excludedGuestsOrExternalUsers else [excludedGuestsOrExternalUsers] } } } } },
          '#withExcludedGuestsOrExternalUsersMixin':: d.fn(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users excluded from scope of policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedGuestsOrExternalUsers', type=d.T.array)]),
          withExcludedGuestsOrExternalUsersMixin(excludedGuestsOrExternalUsers): { spec+: { initProvider+: { conditions+: { users+: { excludedGuestsOrExternalUsers+: if std.isArray(v=excludedGuestsOrExternalUsers) then excludedGuestsOrExternalUsers else [excludedGuestsOrExternalUsers] } } } } },
          '#withExcludedRoles':: d.fn(help='"A list of role IDs excluded from scope of policy."', args=[d.arg(name='excludedRoles', type=d.T.array)]),
          withExcludedRoles(excludedRoles): { spec+: { initProvider+: { conditions+: { users+: { excludedRoles: if std.isArray(v=excludedRoles) then excludedRoles else [excludedRoles] } } } } },
          '#withExcludedRolesMixin':: d.fn(help='"A list of role IDs excluded from scope of policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedRoles', type=d.T.array)]),
          withExcludedRolesMixin(excludedRoles): { spec+: { initProvider+: { conditions+: { users+: { excludedRoles+: if std.isArray(v=excludedRoles) then excludedRoles else [excludedRoles] } } } } },
          '#withExcludedUsers':: d.fn(help='"A list of user IDs excluded from scope of policy and/or GuestsOrExternalUsers."', args=[d.arg(name='excludedUsers', type=d.T.array)]),
          withExcludedUsers(excludedUsers): { spec+: { initProvider+: { conditions+: { users+: { excludedUsers: if std.isArray(v=excludedUsers) then excludedUsers else [excludedUsers] } } } } },
          '#withExcludedUsersMixin':: d.fn(help='"A list of user IDs excluded from scope of policy and/or GuestsOrExternalUsers."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludedUsers', type=d.T.array)]),
          withExcludedUsersMixin(excludedUsers): { spec+: { initProvider+: { conditions+: { users+: { excludedUsers+: if std.isArray(v=excludedUsers) then excludedUsers else [excludedUsers] } } } } },
          '#withIncludedGroups':: d.fn(help='"A list of group IDs in scope of policy unless explicitly excluded."', args=[d.arg(name='includedGroups', type=d.T.array)]),
          withIncludedGroups(includedGroups): { spec+: { initProvider+: { conditions+: { users+: { includedGroups: if std.isArray(v=includedGroups) then includedGroups else [includedGroups] } } } } },
          '#withIncludedGroupsMixin':: d.fn(help='"A list of group IDs in scope of policy unless explicitly excluded."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedGroups', type=d.T.array)]),
          withIncludedGroupsMixin(includedGroups): { spec+: { initProvider+: { conditions+: { users+: { includedGroups+: if std.isArray(v=includedGroups) then includedGroups else [includedGroups] } } } } },
          '#withIncludedGuestsOrExternalUsers':: d.fn(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users in scope of policy."', args=[d.arg(name='includedGuestsOrExternalUsers', type=d.T.array)]),
          withIncludedGuestsOrExternalUsers(includedGuestsOrExternalUsers): { spec+: { initProvider+: { conditions+: { users+: { includedGuestsOrExternalUsers: if std.isArray(v=includedGuestsOrExternalUsers) then includedGuestsOrExternalUsers else [includedGuestsOrExternalUsers] } } } } },
          '#withIncludedGuestsOrExternalUsersMixin':: d.fn(help='"A guests_or_external_users block as documented below, which specifies internal guests and external users in scope of policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedGuestsOrExternalUsers', type=d.T.array)]),
          withIncludedGuestsOrExternalUsersMixin(includedGuestsOrExternalUsers): { spec+: { initProvider+: { conditions+: { users+: { includedGuestsOrExternalUsers+: if std.isArray(v=includedGuestsOrExternalUsers) then includedGuestsOrExternalUsers else [includedGuestsOrExternalUsers] } } } } },
          '#withIncludedRoles':: d.fn(help='"A list of role IDs in scope of policy unless explicitly excluded."', args=[d.arg(name='includedRoles', type=d.T.array)]),
          withIncludedRoles(includedRoles): { spec+: { initProvider+: { conditions+: { users+: { includedRoles: if std.isArray(v=includedRoles) then includedRoles else [includedRoles] } } } } },
          '#withIncludedRolesMixin':: d.fn(help='"A list of role IDs in scope of policy unless explicitly excluded."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedRoles', type=d.T.array)]),
          withIncludedRolesMixin(includedRoles): { spec+: { initProvider+: { conditions+: { users+: { includedRoles+: if std.isArray(v=includedRoles) then includedRoles else [includedRoles] } } } } },
          '#withIncludedUsers':: d.fn(help='"A list of user IDs in scope of policy unless explicitly excluded, or None or All or GuestsOrExternalUsers."', args=[d.arg(name='includedUsers', type=d.T.array)]),
          withIncludedUsers(includedUsers): { spec+: { initProvider+: { conditions+: { users+: { includedUsers: if std.isArray(v=includedUsers) then includedUsers else [includedUsers] } } } } },
          '#withIncludedUsersMixin':: d.fn(help='"A list of user IDs in scope of policy unless explicitly excluded, or None or All or GuestsOrExternalUsers."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedUsers', type=d.T.array)]),
          withIncludedUsersMixin(includedUsers): { spec+: { initProvider+: { conditions+: { users+: { includedUsers+: if std.isArray(v=includedUsers) then includedUsers else [includedUsers] } } } } },
        },
        '#withClientAppTypes':: d.fn(help='"A list of client application types included in the policy. Possible values are: all, browser, mobileAppsAndDesktopClients, exchangeActiveSync, easSupported and other."', args=[d.arg(name='clientAppTypes', type=d.T.array)]),
        withClientAppTypes(clientAppTypes): { spec+: { initProvider+: { conditions+: { clientAppTypes: if std.isArray(v=clientAppTypes) then clientAppTypes else [clientAppTypes] } } } },
        '#withClientAppTypesMixin':: d.fn(help='"A list of client application types included in the policy. Possible values are: all, browser, mobileAppsAndDesktopClients, exchangeActiveSync, easSupported and other."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='clientAppTypes', type=d.T.array)]),
        withClientAppTypesMixin(clientAppTypes): { spec+: { initProvider+: { conditions+: { clientAppTypes+: if std.isArray(v=clientAppTypes) then clientAppTypes else [clientAppTypes] } } } },
        '#withInsiderRiskLevels':: d.fn(help='"The insider risk level in the policy. Possible values are: minor, moderate, elevated, unknownFutureValue."', args=[d.arg(name='insiderRiskLevels', type=d.T.string)]),
        withInsiderRiskLevels(insiderRiskLevels): { spec+: { initProvider+: { conditions+: { insiderRiskLevels: insiderRiskLevels } } } },
        '#withServicePrincipalRiskLevels':: d.fn(help='"A list of service principal sign-in risk levels included in the policy. Possible values are: low, medium, high, none, unknownFutureValue."', args=[d.arg(name='servicePrincipalRiskLevels', type=d.T.array)]),
        withServicePrincipalRiskLevels(servicePrincipalRiskLevels): { spec+: { initProvider+: { conditions+: { servicePrincipalRiskLevels: if std.isArray(v=servicePrincipalRiskLevels) then servicePrincipalRiskLevels else [servicePrincipalRiskLevels] } } } },
        '#withServicePrincipalRiskLevelsMixin':: d.fn(help='"A list of service principal sign-in risk levels included in the policy. Possible values are: low, medium, high, none, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='servicePrincipalRiskLevels', type=d.T.array)]),
        withServicePrincipalRiskLevelsMixin(servicePrincipalRiskLevels): { spec+: { initProvider+: { conditions+: { servicePrincipalRiskLevels+: if std.isArray(v=servicePrincipalRiskLevels) then servicePrincipalRiskLevels else [servicePrincipalRiskLevels] } } } },
        '#withSignInRiskLevels':: d.fn(help='"A list of user sign-in risk levels included in the policy. Possible values are: low, medium, high, hidden, none, unknownFutureValue."', args=[d.arg(name='signInRiskLevels', type=d.T.array)]),
        withSignInRiskLevels(signInRiskLevels): { spec+: { initProvider+: { conditions+: { signInRiskLevels: if std.isArray(v=signInRiskLevels) then signInRiskLevels else [signInRiskLevels] } } } },
        '#withSignInRiskLevelsMixin':: d.fn(help='"A list of user sign-in risk levels included in the policy. Possible values are: low, medium, high, hidden, none, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='signInRiskLevels', type=d.T.array)]),
        withSignInRiskLevelsMixin(signInRiskLevels): { spec+: { initProvider+: { conditions+: { signInRiskLevels+: if std.isArray(v=signInRiskLevels) then signInRiskLevels else [signInRiskLevels] } } } },
        '#withUserRiskLevels':: d.fn(help='"A list of user risk levels included in the policy. Possible values are: low, medium, high, hidden, none, unknownFutureValue."', args=[d.arg(name='userRiskLevels', type=d.T.array)]),
        withUserRiskLevels(userRiskLevels): { spec+: { initProvider+: { conditions+: { userRiskLevels: if std.isArray(v=userRiskLevels) then userRiskLevels else [userRiskLevels] } } } },
        '#withUserRiskLevelsMixin':: d.fn(help='"A list of user risk levels included in the policy. Possible values are: low, medium, high, hidden, none, unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='userRiskLevels', type=d.T.array)]),
        withUserRiskLevelsMixin(userRiskLevels): { spec+: { initProvider+: { conditions+: { userRiskLevels+: if std.isArray(v=userRiskLevels) then userRiskLevels else [userRiskLevels] } } } },
      },
      '#grantControls':: d.obj(help='"A grant_controls block as documented below, which specifies the grant controls that must be fulfilled to pass the policy."'),
      grantControls: {
        '#withAuthenticationStrengthPolicyId':: d.fn(help='"ID of an Authentication Strength Policy to use in this policy. When using a hard-coded ID, the UUID value should be prefixed with: /policies/authenticationStrengthPolicies/."', args=[d.arg(name='authenticationStrengthPolicyId', type=d.T.string)]),
        withAuthenticationStrengthPolicyId(authenticationStrengthPolicyId): { spec+: { initProvider+: { grantControls+: { authenticationStrengthPolicyId: authenticationStrengthPolicyId } } } },
        '#withBuiltInControls':: d.fn(help='"List of built-in controls required by the policy. Possible values are: block, mfa, approvedApplication, compliantApplication, compliantDevice, domainJoinedDevice, passwordChange or unknownFutureValue."', args=[d.arg(name='builtInControls', type=d.T.array)]),
        withBuiltInControls(builtInControls): { spec+: { initProvider+: { grantControls+: { builtInControls: if std.isArray(v=builtInControls) then builtInControls else [builtInControls] } } } },
        '#withBuiltInControlsMixin':: d.fn(help='"List of built-in controls required by the policy. Possible values are: block, mfa, approvedApplication, compliantApplication, compliantDevice, domainJoinedDevice, passwordChange or unknownFutureValue."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='builtInControls', type=d.T.array)]),
        withBuiltInControlsMixin(builtInControls): { spec+: { initProvider+: { grantControls+: { builtInControls+: if std.isArray(v=builtInControls) then builtInControls else [builtInControls] } } } },
        '#withCustomAuthenticationFactors':: d.fn(help='"List of custom controls IDs required by the policy."', args=[d.arg(name='customAuthenticationFactors', type=d.T.array)]),
        withCustomAuthenticationFactors(customAuthenticationFactors): { spec+: { initProvider+: { grantControls+: { customAuthenticationFactors: if std.isArray(v=customAuthenticationFactors) then customAuthenticationFactors else [customAuthenticationFactors] } } } },
        '#withCustomAuthenticationFactorsMixin':: d.fn(help='"List of custom controls IDs required by the policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='customAuthenticationFactors', type=d.T.array)]),
        withCustomAuthenticationFactorsMixin(customAuthenticationFactors): { spec+: { initProvider+: { grantControls+: { customAuthenticationFactors+: if std.isArray(v=customAuthenticationFactors) then customAuthenticationFactors else [customAuthenticationFactors] } } } },
        '#withOperator':: d.fn(help='"Defines the relationship of the grant controls. Possible values are: AND, OR."', args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { spec+: { initProvider+: { grantControls+: { operator: operator } } } },
        '#withTermsOfUse':: d.fn(help='"List of terms of use IDs required by the policy."', args=[d.arg(name='termsOfUse', type=d.T.array)]),
        withTermsOfUse(termsOfUse): { spec+: { initProvider+: { grantControls+: { termsOfUse: if std.isArray(v=termsOfUse) then termsOfUse else [termsOfUse] } } } },
        '#withTermsOfUseMixin':: d.fn(help='"List of terms of use IDs required by the policy."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='termsOfUse', type=d.T.array)]),
        withTermsOfUseMixin(termsOfUse): { spec+: { initProvider+: { grantControls+: { termsOfUse+: if std.isArray(v=termsOfUse) then termsOfUse else [termsOfUse] } } } },
      },
      '#sessionControls':: d.obj(help='"A session_controls block as documented below, which specifies the session controls that are enforced after sign-in."'),
      sessionControls: {
        '#withApplicationEnforcedRestrictionsEnabled':: d.fn(help='"Whether application enforced restrictions are enabled. Defaults to false."', args=[d.arg(name='applicationEnforcedRestrictionsEnabled', type=d.T.boolean)]),
        withApplicationEnforcedRestrictionsEnabled(applicationEnforcedRestrictionsEnabled): { spec+: { initProvider+: { sessionControls+: { applicationEnforcedRestrictionsEnabled: applicationEnforcedRestrictionsEnabled } } } },
        '#withCloudAppSecurityPolicy':: d.fn(help='"Enables cloud app security and specifies the cloud app security policy to use. Possible values are: blockDownloads, mcasConfigured, monitorOnly or unknownFutureValue."', args=[d.arg(name='cloudAppSecurityPolicy', type=d.T.string)]),
        withCloudAppSecurityPolicy(cloudAppSecurityPolicy): { spec+: { initProvider+: { sessionControls+: { cloudAppSecurityPolicy: cloudAppSecurityPolicy } } } },
        '#withDisableResilienceDefaults':: d.fn(help='"Disables resilience defaults. Defaults to false."', args=[d.arg(name='disableResilienceDefaults', type=d.T.boolean)]),
        withDisableResilienceDefaults(disableResilienceDefaults): { spec+: { initProvider+: { sessionControls+: { disableResilienceDefaults: disableResilienceDefaults } } } },
        '#withPersistentBrowserMode':: d.fn(help='"Session control to define whether to persist cookies. Possible values are: always or never."', args=[d.arg(name='persistentBrowserMode', type=d.T.string)]),
        withPersistentBrowserMode(persistentBrowserMode): { spec+: { initProvider+: { sessionControls+: { persistentBrowserMode: persistentBrowserMode } } } },
        '#withSignInFrequency':: d.fn(help='"Number of days or hours to enforce sign-in frequency. Required when sign_in_frequency_period is specified."', args=[d.arg(name='signInFrequency', type=d.T.number)]),
        withSignInFrequency(signInFrequency): { spec+: { initProvider+: { sessionControls+: { signInFrequency: signInFrequency } } } },
        '#withSignInFrequencyAuthenticationType':: d.fn(help='"Authentication type for enforcing sign-in frequency. Possible values are: primaryAndSecondaryAuthentication or secondaryAuthentication. Defaults to primaryAndSecondaryAuthentication."', args=[d.arg(name='signInFrequencyAuthenticationType', type=d.T.string)]),
        withSignInFrequencyAuthenticationType(signInFrequencyAuthenticationType): { spec+: { initProvider+: { sessionControls+: { signInFrequencyAuthenticationType: signInFrequencyAuthenticationType } } } },
        '#withSignInFrequencyInterval':: d.fn(help='"The interval to apply to sign-in frequency control. Possible values are: timeBased or everyTime. Defaults to timeBased."', args=[d.arg(name='signInFrequencyInterval', type=d.T.string)]),
        withSignInFrequencyInterval(signInFrequencyInterval): { spec+: { initProvider+: { sessionControls+: { signInFrequencyInterval: signInFrequencyInterval } } } },
        '#withSignInFrequencyPeriod':: d.fn(help='"The time period to enforce sign-in frequency. Possible values are: hours or days. Required when sign_in_frequency_period is specified."', args=[d.arg(name='signInFrequencyPeriod', type=d.T.string)]),
        withSignInFrequencyPeriod(signInFrequencyPeriod): { spec+: { initProvider+: { sessionControls+: { signInFrequencyPeriod: signInFrequencyPeriod } } } },
      },
      '#withDisplayName':: d.fn(help='"The friendly name for this Conditional Access Policy."', args=[d.arg(name='displayName', type=d.T.string)]),
      withDisplayName(displayName): { spec+: { initProvider+: { displayName: displayName } } },
      '#withState':: d.fn(help='"Specifies the state of the policy object. Possible values are: enabled, disabled and enabledForReportingButNotEnforced"', args=[d.arg(name='state', type=d.T.string)]),
      withState(state): { spec+: { initProvider+: { state: state } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to\\ncreate, observe, update, and delete this managed resource should be\\nconfigured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external\\nwhen this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the\\nexternal resource.\\nThis field is planned to be deprecated in favor of the ManagementPolicies\\nfield in a future release. Currently, both could be set independently and\\nnon-default values would be honored if the feature flag is enabled.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a\\nSecret to which any connection details for this managed resource should\\nbe written. Connection details frequently include the endpoint, username,\\nand password required to connect to the managed resource."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
