{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='groupRoleManagementPolicy', url='', help='"GroupRoleManagementPolicy is the Schema for the GroupRoleManagementPolicys API."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of GroupRoleManagementPolicy', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'policies.azuread.upbound.io/v1beta1',
    kind: 'GroupRoleManagementPolicy',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"GroupRoleManagementPolicySpec defines the desired state of GroupRoleManagementPolicy"'),
  spec: {
    '#forProvider':: d.obj(help=''),
    forProvider: {
      '#activationRules':: d.obj(help='"An activation_rules block as defined below.\\nThe activation rules of the policy"'),
      activationRules: {
        '#approvalStage':: d.obj(help='"An approval_stage block as defined below.\\nThe approval stages for the activation"'),
        approvalStage: {
          '#primaryApprover':: d.obj(help='"blocks as defined below.\\nThe IDs of the users or groups who can approve the activation"'),
          primaryApprover: {
            '#withObjectId':: d.fn(help='"The ID of the object which will act as an approver.\\nThe ID of the object to act as an approver"', args=[d.arg(name='objectId', type=d.T.string)]),
            withObjectId(objectId): { objectId: objectId },
            '#withType':: d.fn(help='"The type of object acting as an approver. Possible options are singleUser and groupMembers.\\nThe type of object acting as an approver"', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { type: type },
          },
          '#withPrimaryApprover':: d.fn(help='"blocks as defined below.\\nThe IDs of the users or groups who can approve the activation"', args=[d.arg(name='primaryApprover', type=d.T.array)]),
          withPrimaryApprover(primaryApprover): { spec+: { forProvider+: { activationRules+: { approvalStage+: { primaryApprover: if std.isArray(v=primaryApprover) then primaryApprover else [primaryApprover] } } } } },
          '#withPrimaryApproverMixin':: d.fn(help='"blocks as defined below.\\nThe IDs of the users or groups who can approve the activation"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='primaryApprover', type=d.T.array)]),
          withPrimaryApproverMixin(primaryApprover): { spec+: { forProvider+: { activationRules+: { approvalStage+: { primaryApprover+: if std.isArray(v=primaryApprover) then primaryApprover else [primaryApprover] } } } } },
        },
        '#withMaximumDuration':: d.fn(help='"The maximum length of time an activated role can be valid, in an ISO8601 Duration format (e.g. PT8H). Valid range is PT30M to PT23H30M, in 30 minute increments, or PT1D.\\nThe time after which the an activation can be valid for"', args=[d.arg(name='maximumDuration', type=d.T.string)]),
        withMaximumDuration(maximumDuration): { spec+: { forProvider+: { activationRules+: { maximumDuration: maximumDuration } } } },
        '#withRequireApproval':: d.fn(help='"Is approval required for activation. If true an approval_stage block must be provided.\\nWhether an approval is required for activation"', args=[d.arg(name='requireApproval', type=d.T.boolean)]),
        withRequireApproval(requireApproval): { spec+: { forProvider+: { activationRules+: { requireApproval: requireApproval } } } },
        '#withRequireJustification':: d.fn(help='"Is a justification required during activation of the role.\\nWhether a justification is required during activation"', args=[d.arg(name='requireJustification', type=d.T.boolean)]),
        withRequireJustification(requireJustification): { spec+: { forProvider+: { activationRules+: { requireJustification: requireJustification } } } },
        '#withRequireMultifactorAuthentication':: d.fn(help='"Is multi-factor authentication required to activate the role. Conflicts with required_conditional_access_authentication_context.\\nWhether multi-factor authentication is required during activation"', args=[d.arg(name='requireMultifactorAuthentication', type=d.T.boolean)]),
        withRequireMultifactorAuthentication(requireMultifactorAuthentication): { spec+: { forProvider+: { activationRules+: { requireMultifactorAuthentication: requireMultifactorAuthentication } } } },
        '#withRequireTicketInfo':: d.fn(help='"Is ticket information requrired during activation of the role.\\nWhether ticket information is required during activation"', args=[d.arg(name='requireTicketInfo', type=d.T.boolean)]),
        withRequireTicketInfo(requireTicketInfo): { spec+: { forProvider+: { activationRules+: { requireTicketInfo: requireTicketInfo } } } },
        '#withRequiredConditionalAccessAuthenticationContext':: d.fn(help='"The Entra ID Conditional Access context that must be present for activation (e.g c1). Conflicts with require_multifactor_authentication.\\nWhether a conditional access context is required during activation"', args=[d.arg(name='requiredConditionalAccessAuthenticationContext', type=d.T.string)]),
        withRequiredConditionalAccessAuthenticationContext(requiredConditionalAccessAuthenticationContext): { spec+: { forProvider+: { activationRules+: { requiredConditionalAccessAuthenticationContext: requiredConditionalAccessAuthenticationContext } } } },
      },
      '#activeAssignmentRules':: d.obj(help='"An active_assignment_rules block as defined below.\\nThe rules for active assignment of the policy"'),
      activeAssignmentRules: {
        '#withExpirationRequired':: d.fn(help='"Must an assignment have an expiry date. false allows permanent assignment.\\nMust the assignment have an expiry date"', args=[d.arg(name='expirationRequired', type=d.T.boolean)]),
        withExpirationRequired(expirationRequired): { spec+: { forProvider+: { activeAssignmentRules+: { expirationRequired: expirationRequired } } } },
        '#withExpireAfter':: d.fn(help='"The maximum length of time an assignment can be valid, as an ISO8601 duration. Permitted values: P15D, P30D, P90D, P180D, or P365D.\\nThe duration after which assignments expire"', args=[d.arg(name='expireAfter', type=d.T.string)]),
        withExpireAfter(expireAfter): { spec+: { forProvider+: { activeAssignmentRules+: { expireAfter: expireAfter } } } },
        '#withRequireJustification':: d.fn(help='"Is a justification required to create new assignments.\\nWhether a justification is required to make an assignment"', args=[d.arg(name='requireJustification', type=d.T.boolean)]),
        withRequireJustification(requireJustification): { spec+: { forProvider+: { activeAssignmentRules+: { requireJustification: requireJustification } } } },
        '#withRequireMultifactorAuthentication':: d.fn(help='"Is multi-factor authentication required to create new assignments.\\nWhether multi-factor authentication is required to make an assignment"', args=[d.arg(name='requireMultifactorAuthentication', type=d.T.boolean)]),
        withRequireMultifactorAuthentication(requireMultifactorAuthentication): { spec+: { forProvider+: { activeAssignmentRules+: { requireMultifactorAuthentication: requireMultifactorAuthentication } } } },
        '#withRequireTicketInfo':: d.fn(help='"Is ticket information required to create new assignments.\\nWhether ticket information is required to make an assignment"', args=[d.arg(name='requireTicketInfo', type=d.T.boolean)]),
        withRequireTicketInfo(requireTicketInfo): { spec+: { forProvider+: { activeAssignmentRules+: { requireTicketInfo: requireTicketInfo } } } },
      },
      '#eligibleAssignmentRules':: d.obj(help='"An eligible_assignment_rules block as defined below.\\nThe rules for eligible assignment of the policy"'),
      eligibleAssignmentRules: {
        '#withExpirationRequired':: d.fn(help='"Must an assignment have an expiry date. false allows permanent assignment.\\nMust the assignment have an expiry date"', args=[d.arg(name='expirationRequired', type=d.T.boolean)]),
        withExpirationRequired(expirationRequired): { spec+: { forProvider+: { eligibleAssignmentRules+: { expirationRequired: expirationRequired } } } },
        '#withExpireAfter':: d.fn(help='"The maximum length of time an assignment can be valid, as an ISO8601 duration. Permitted values: P15D, P30D, P90D, P180D, or P365D.\\nThe duration after which assignments expire"', args=[d.arg(name='expireAfter', type=d.T.string)]),
        withExpireAfter(expireAfter): { spec+: { forProvider+: { eligibleAssignmentRules+: { expireAfter: expireAfter } } } },
      },
      '#groupIdRef':: d.obj(help='"Reference to a Group in groups to populate groupId."'),
      groupIdRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { groupIdRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { groupIdRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { forProvider+: { groupIdRef+: { name: name } } } },
      },
      '#groupIdSelector':: d.obj(help='"Selector for a Group in groups to populate groupId."'),
      groupIdSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { forProvider+: { groupIdSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { forProvider+: { groupIdSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { forProvider+: { groupIdSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { forProvider+: { groupIdSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { forProvider+: { groupIdSelector+: { matchLabels+: matchLabels } } } },
      },
      '#notificationRules':: d.obj(help='"A notification_rules block as defined below.\\nThe notification rules of the policy"'),
      notificationRules: {
        '#activeAssignments':: d.obj(help='"A notification_target block as defined below to configure notfications on active role assignments.\\nNotifications about active assignments"'),
        activeAssignments: {
          '#adminNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAdmin notification settings"'),
          adminNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { adminNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { adminNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { adminNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { adminNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#approverNotifications':: d.obj(help='"A notification_settings block as defined above.\\nApprover notification settings"'),
          approverNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { approverNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { approverNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { approverNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { approverNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#assigneeNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAssignee notification settings"'),
          assigneeNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { assigneeNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { assigneeNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { assigneeNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { forProvider+: { notificationRules+: { activeAssignments+: { assigneeNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
        },
        '#eligibleActivations':: d.obj(help='"A notification_target block as defined below for configuring notifications on activation of eligible role.\\nNotifications about activations of eligible assignments"'),
        eligibleActivations: {
          '#adminNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAdmin notification settings"'),
          adminNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { adminNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { adminNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { adminNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { adminNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#approverNotifications':: d.obj(help='"A notification_settings block as defined above.\\nApprover notification settings"'),
          approverNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { approverNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { approverNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { approverNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { approverNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#assigneeNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAssignee notification settings"'),
          assigneeNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { assigneeNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { assigneeNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { assigneeNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { forProvider+: { notificationRules+: { eligibleActivations+: { assigneeNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
        },
        '#eligibleAssignments':: d.obj(help='"A notification_target block as defined below to configure notification on eligible role assignments.\\nNotifications about eligible assignments"'),
        eligibleAssignments: {
          '#adminNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAdmin notification settings"'),
          adminNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { adminNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { adminNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { adminNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { adminNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#approverNotifications':: d.obj(help='"A notification_settings block as defined above.\\nApprover notification settings"'),
          approverNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { approverNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { approverNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { approverNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { approverNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#assigneeNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAssignee notification settings"'),
          assigneeNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { assigneeNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { assigneeNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { assigneeNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { forProvider+: { notificationRules+: { eligibleAssignments+: { assigneeNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
        },
      },
      '#withGroupId':: d.fn(help='"The ID of the Azure AD group for which the policy applies.\\nID of the group to which this policy is assigned"', args=[d.arg(name='groupId', type=d.T.string)]),
      withGroupId(groupId): { spec+: { forProvider+: { groupId: groupId } } },
      '#withRoleId':: d.fn(help='"The type of assignment this policy coveres. Can be either member or owner.\\nThe ID of the role of this policy to the group"', args=[d.arg(name='roleId', type=d.T.string)]),
      withRoleId(roleId): { spec+: { forProvider+: { roleId: roleId } } },
    },
    '#initProvider':: d.obj(help='"THIS IS A BETA FIELD. It will be honored\\nunless the Management Policies feature flag is disabled.\\nInitProvider holds the same fields as ForProvider, with the exception\\nof Identifier and other resource reference fields. The fields that are\\nin InitProvider are merged into ForProvider when the resource is created.\\nThe same fields are also added to the terraform ignore_changes hook, to\\navoid updating them after creation. This is useful for fields that are\\nrequired on creation, but we do not desire to update them after creation,\\nfor example because of an external controller is managing them, like an\\nautoscaler."'),
    initProvider: {
      '#activationRules':: d.obj(help='"An activation_rules block as defined below.\\nThe activation rules of the policy"'),
      activationRules: {
        '#approvalStage':: d.obj(help='"An approval_stage block as defined below.\\nThe approval stages for the activation"'),
        approvalStage: {
          '#primaryApprover':: d.obj(help='"blocks as defined below.\\nThe IDs of the users or groups who can approve the activation"'),
          primaryApprover: {
            '#withObjectId':: d.fn(help='"The ID of the object which will act as an approver.\\nThe ID of the object to act as an approver"', args=[d.arg(name='objectId', type=d.T.string)]),
            withObjectId(objectId): { objectId: objectId },
            '#withType':: d.fn(help='"The type of object acting as an approver. Possible options are singleUser and groupMembers.\\nThe type of object acting as an approver"', args=[d.arg(name='type', type=d.T.string)]),
            withType(type): { type: type },
          },
          '#withPrimaryApprover':: d.fn(help='"blocks as defined below.\\nThe IDs of the users or groups who can approve the activation"', args=[d.arg(name='primaryApprover', type=d.T.array)]),
          withPrimaryApprover(primaryApprover): { spec+: { initProvider+: { activationRules+: { approvalStage+: { primaryApprover: if std.isArray(v=primaryApprover) then primaryApprover else [primaryApprover] } } } } },
          '#withPrimaryApproverMixin':: d.fn(help='"blocks as defined below.\\nThe IDs of the users or groups who can approve the activation"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='primaryApprover', type=d.T.array)]),
          withPrimaryApproverMixin(primaryApprover): { spec+: { initProvider+: { activationRules+: { approvalStage+: { primaryApprover+: if std.isArray(v=primaryApprover) then primaryApprover else [primaryApprover] } } } } },
        },
        '#withMaximumDuration':: d.fn(help='"The maximum length of time an activated role can be valid, in an ISO8601 Duration format (e.g. PT8H). Valid range is PT30M to PT23H30M, in 30 minute increments, or PT1D.\\nThe time after which the an activation can be valid for"', args=[d.arg(name='maximumDuration', type=d.T.string)]),
        withMaximumDuration(maximumDuration): { spec+: { initProvider+: { activationRules+: { maximumDuration: maximumDuration } } } },
        '#withRequireApproval':: d.fn(help='"Is approval required for activation. If true an approval_stage block must be provided.\\nWhether an approval is required for activation"', args=[d.arg(name='requireApproval', type=d.T.boolean)]),
        withRequireApproval(requireApproval): { spec+: { initProvider+: { activationRules+: { requireApproval: requireApproval } } } },
        '#withRequireJustification':: d.fn(help='"Is a justification required during activation of the role.\\nWhether a justification is required during activation"', args=[d.arg(name='requireJustification', type=d.T.boolean)]),
        withRequireJustification(requireJustification): { spec+: { initProvider+: { activationRules+: { requireJustification: requireJustification } } } },
        '#withRequireMultifactorAuthentication':: d.fn(help='"Is multi-factor authentication required to activate the role. Conflicts with required_conditional_access_authentication_context.\\nWhether multi-factor authentication is required during activation"', args=[d.arg(name='requireMultifactorAuthentication', type=d.T.boolean)]),
        withRequireMultifactorAuthentication(requireMultifactorAuthentication): { spec+: { initProvider+: { activationRules+: { requireMultifactorAuthentication: requireMultifactorAuthentication } } } },
        '#withRequireTicketInfo':: d.fn(help='"Is ticket information requrired during activation of the role.\\nWhether ticket information is required during activation"', args=[d.arg(name='requireTicketInfo', type=d.T.boolean)]),
        withRequireTicketInfo(requireTicketInfo): { spec+: { initProvider+: { activationRules+: { requireTicketInfo: requireTicketInfo } } } },
        '#withRequiredConditionalAccessAuthenticationContext':: d.fn(help='"The Entra ID Conditional Access context that must be present for activation (e.g c1). Conflicts with require_multifactor_authentication.\\nWhether a conditional access context is required during activation"', args=[d.arg(name='requiredConditionalAccessAuthenticationContext', type=d.T.string)]),
        withRequiredConditionalAccessAuthenticationContext(requiredConditionalAccessAuthenticationContext): { spec+: { initProvider+: { activationRules+: { requiredConditionalAccessAuthenticationContext: requiredConditionalAccessAuthenticationContext } } } },
      },
      '#activeAssignmentRules':: d.obj(help='"An active_assignment_rules block as defined below.\\nThe rules for active assignment of the policy"'),
      activeAssignmentRules: {
        '#withExpirationRequired':: d.fn(help='"Must an assignment have an expiry date. false allows permanent assignment.\\nMust the assignment have an expiry date"', args=[d.arg(name='expirationRequired', type=d.T.boolean)]),
        withExpirationRequired(expirationRequired): { spec+: { initProvider+: { activeAssignmentRules+: { expirationRequired: expirationRequired } } } },
        '#withExpireAfter':: d.fn(help='"The maximum length of time an assignment can be valid, as an ISO8601 duration. Permitted values: P15D, P30D, P90D, P180D, or P365D.\\nThe duration after which assignments expire"', args=[d.arg(name='expireAfter', type=d.T.string)]),
        withExpireAfter(expireAfter): { spec+: { initProvider+: { activeAssignmentRules+: { expireAfter: expireAfter } } } },
        '#withRequireJustification':: d.fn(help='"Is a justification required to create new assignments.\\nWhether a justification is required to make an assignment"', args=[d.arg(name='requireJustification', type=d.T.boolean)]),
        withRequireJustification(requireJustification): { spec+: { initProvider+: { activeAssignmentRules+: { requireJustification: requireJustification } } } },
        '#withRequireMultifactorAuthentication':: d.fn(help='"Is multi-factor authentication required to create new assignments.\\nWhether multi-factor authentication is required to make an assignment"', args=[d.arg(name='requireMultifactorAuthentication', type=d.T.boolean)]),
        withRequireMultifactorAuthentication(requireMultifactorAuthentication): { spec+: { initProvider+: { activeAssignmentRules+: { requireMultifactorAuthentication: requireMultifactorAuthentication } } } },
        '#withRequireTicketInfo':: d.fn(help='"Is ticket information required to create new assignments.\\nWhether ticket information is required to make an assignment"', args=[d.arg(name='requireTicketInfo', type=d.T.boolean)]),
        withRequireTicketInfo(requireTicketInfo): { spec+: { initProvider+: { activeAssignmentRules+: { requireTicketInfo: requireTicketInfo } } } },
      },
      '#eligibleAssignmentRules':: d.obj(help='"An eligible_assignment_rules block as defined below.\\nThe rules for eligible assignment of the policy"'),
      eligibleAssignmentRules: {
        '#withExpirationRequired':: d.fn(help='"Must an assignment have an expiry date. false allows permanent assignment.\\nMust the assignment have an expiry date"', args=[d.arg(name='expirationRequired', type=d.T.boolean)]),
        withExpirationRequired(expirationRequired): { spec+: { initProvider+: { eligibleAssignmentRules+: { expirationRequired: expirationRequired } } } },
        '#withExpireAfter':: d.fn(help='"The maximum length of time an assignment can be valid, as an ISO8601 duration. Permitted values: P15D, P30D, P90D, P180D, or P365D.\\nThe duration after which assignments expire"', args=[d.arg(name='expireAfter', type=d.T.string)]),
        withExpireAfter(expireAfter): { spec+: { initProvider+: { eligibleAssignmentRules+: { expireAfter: expireAfter } } } },
      },
      '#groupIdRef':: d.obj(help='"Reference to a Group in groups to populate groupId."'),
      groupIdRef: {
        '#policy':: d.obj(help='"Policies for referencing."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { groupIdRef+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { groupIdRef+: { policy+: { resolve: resolve } } } } },
        },
        '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { initProvider+: { groupIdRef+: { name: name } } } },
      },
      '#groupIdSelector':: d.obj(help='"Selector for a Group in groups to populate groupId."'),
      groupIdSelector: {
        '#policy':: d.obj(help='"Policies for selection."'),
        policy: {
          '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
          withResolution(resolution): { spec+: { initProvider+: { groupIdSelector+: { policy+: { resolution: resolution } } } } },
          '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
          withResolve(resolve): { spec+: { initProvider+: { groupIdSelector+: { policy+: { resolve: resolve } } } } },
        },
        '#withMatchControllerRef':: d.fn(help='"MatchControllerRef ensures an object with the same controller reference\\nas the selecting object is selected."', args=[d.arg(name='matchControllerRef', type=d.T.boolean)]),
        withMatchControllerRef(matchControllerRef): { spec+: { initProvider+: { groupIdSelector+: { matchControllerRef: matchControllerRef } } } },
        '#withMatchLabels':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabels(matchLabels): { spec+: { initProvider+: { groupIdSelector+: { matchLabels: matchLabels } } } },
        '#withMatchLabelsMixin':: d.fn(help='"MatchLabels ensures an object with matching labels is selected."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
        withMatchLabelsMixin(matchLabels): { spec+: { initProvider+: { groupIdSelector+: { matchLabels+: matchLabels } } } },
      },
      '#notificationRules':: d.obj(help='"A notification_rules block as defined below.\\nThe notification rules of the policy"'),
      notificationRules: {
        '#activeAssignments':: d.obj(help='"A notification_target block as defined below to configure notfications on active role assignments.\\nNotifications about active assignments"'),
        activeAssignments: {
          '#adminNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAdmin notification settings"'),
          adminNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { adminNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { adminNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { adminNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { adminNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#approverNotifications':: d.obj(help='"A notification_settings block as defined above.\\nApprover notification settings"'),
          approverNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { approverNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { approverNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { approverNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { approverNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#assigneeNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAssignee notification settings"'),
          assigneeNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { assigneeNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { assigneeNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { assigneeNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { initProvider+: { notificationRules+: { activeAssignments+: { assigneeNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
        },
        '#eligibleActivations':: d.obj(help='"A notification_target block as defined below for configuring notifications on activation of eligible role.\\nNotifications about activations of eligible assignments"'),
        eligibleActivations: {
          '#adminNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAdmin notification settings"'),
          adminNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { adminNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { adminNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { adminNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { adminNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#approverNotifications':: d.obj(help='"A notification_settings block as defined above.\\nApprover notification settings"'),
          approverNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { approverNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { approverNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { approverNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { approverNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#assigneeNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAssignee notification settings"'),
          assigneeNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { assigneeNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { assigneeNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { assigneeNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { initProvider+: { notificationRules+: { eligibleActivations+: { assigneeNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
        },
        '#eligibleAssignments':: d.obj(help='"A notification_target block as defined below to configure notification on eligible role assignments.\\nNotifications about eligible assignments"'),
        eligibleAssignments: {
          '#adminNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAdmin notification settings"'),
          adminNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { adminNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { adminNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { adminNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { adminNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#approverNotifications':: d.obj(help='"A notification_settings block as defined above.\\nApprover notification settings"'),
          approverNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { approverNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { approverNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { approverNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { approverNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
          '#assigneeNotifications':: d.obj(help='"A notification_settings block as defined above.\\nAssignee notification settings"'),
          assigneeNotifications: {
            '#withAdditionalRecipients':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipients(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { assigneeNotifications+: { additionalRecipients: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withAdditionalRecipientsMixin':: d.fn(help='"A list of additional email addresses that will receive these notifications.\\nThe additional recipients to notify"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='additionalRecipients', type=d.T.array)]),
            withAdditionalRecipientsMixin(additionalRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { assigneeNotifications+: { additionalRecipients+: if std.isArray(v=additionalRecipients) then additionalRecipients else [additionalRecipients] } } } } } },
            '#withDefaultRecipients':: d.fn(help='"Should the default recipients receive these notifications.\\nWhether the default recipients are notified"', args=[d.arg(name='defaultRecipients', type=d.T.boolean)]),
            withDefaultRecipients(defaultRecipients): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { assigneeNotifications+: { defaultRecipients: defaultRecipients } } } } } },
            '#withNotificationLevel':: d.fn(help='"What level of notifications should be sent. Options are All or Critical.\\nWhat level of notifications are sent"', args=[d.arg(name='notificationLevel', type=d.T.string)]),
            withNotificationLevel(notificationLevel): { spec+: { initProvider+: { notificationRules+: { eligibleAssignments+: { assigneeNotifications+: { notificationLevel: notificationLevel } } } } } },
          },
        },
      },
      '#withGroupId':: d.fn(help='"The ID of the Azure AD group for which the policy applies.\\nID of the group to which this policy is assigned"', args=[d.arg(name='groupId', type=d.T.string)]),
      withGroupId(groupId): { spec+: { initProvider+: { groupId: groupId } } },
      '#withRoleId':: d.fn(help='"The type of assignment this policy coveres. Can be either member or owner.\\nThe ID of the role of this policy to the group"', args=[d.arg(name='roleId', type=d.T.string)]),
      withRoleId(roleId): { spec+: { initProvider+: { roleId: roleId } } },
    },
    '#providerConfigRef':: d.obj(help='"ProviderConfigReference specifies how the provider that will be used to\\ncreate, observe, update, and delete this managed resource should be\\nconfigured."'),
    providerConfigRef: {
      '#policy':: d.obj(help='"Policies for referencing."'),
      policy: {
        '#withResolution':: d.fn(help="\"Resolution specifies whether resolution of this reference is required.\\nThe default is 'Required', which means the reconcile will fail if the\\nreference cannot be resolved. 'Optional' means this reference will be\\na no-op if it cannot be resolved.\"", args=[d.arg(name='resolution', type=d.T.string)]),
        withResolution(resolution): { spec+: { providerConfigRef+: { policy+: { resolution: resolution } } } },
        '#withResolve':: d.fn(help="\"Resolve specifies when this reference should be resolved. The default\\nis 'IfNotPresent', which will attempt to resolve the reference only when\\nthe corresponding field is not present. Use 'Always' to resolve the\\nreference on every reconcile.\"", args=[d.arg(name='resolve', type=d.T.string)]),
        withResolve(resolve): { spec+: { providerConfigRef+: { policy+: { resolve: resolve } } } },
      },
      '#withName':: d.fn(help='"Name of the referenced object."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { providerConfigRef+: { name: name } } },
    },
    '#withDeletionPolicy':: d.fn(help='"DeletionPolicy specifies what will happen to the underlying external\\nwhen this managed resource is deleted - either \\"Delete\\" or \\"Orphan\\" the\\nexternal resource.\\nThis field is planned to be deprecated in favor of the ManagementPolicies\\nfield in a future release. Currently, both could be set independently and\\nnon-default values would be honored if the feature flag is enabled.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223"', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withManagementPolicies':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPolicies(managementPolicies): { spec+: { managementPolicies: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#withManagementPoliciesMixin':: d.fn(help='"THIS IS A BETA FIELD. It is on by default but can be opted out\\nthrough a Crossplane feature flag.\\nManagementPolicies specify the array of actions Crossplane is allowed to\\ntake on the managed and external resources.\\nThis field is planned to replace the DeletionPolicy field in a future\\nrelease. Currently, both could be set independently and non-default\\nvalues would be honored if the feature flag is enabled. If both are\\ncustom, the DeletionPolicy field will be ignored.\\nSee the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223\\nand this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managementPolicies', type=d.T.array)]),
    withManagementPoliciesMixin(managementPolicies): { spec+: { managementPolicies+: if std.isArray(v=managementPolicies) then managementPolicies else [managementPolicies] } },
    '#writeConnectionSecretToRef':: d.obj(help='"WriteConnectionSecretToReference specifies the namespace and name of a\\nSecret to which any connection details for this managed resource should\\nbe written. Connection details frequently include the endpoint, username,\\nand password required to connect to the managed resource."'),
    writeConnectionSecretToRef: {
      '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { writeConnectionSecretToRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { writeConnectionSecretToRef+: { namespace: namespace } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
